Get a list of search results
sforzando/q-lako pull request #20
Opened 2020-11-15 18:42 UTC by yusuke-sforzando

## Describe the PR

To close #3.
Get a list of search results using the Amazon API.

## Screenshots

(T.B.D.)

## Detail of the change

(T.B.D.)

## Anticipated impacts

(T.B.D.)

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D.)

2020-11-17 03:34 UTC, tomoya-sforzando requested changes
コメントバックします

2020-11-17 03:34 UTC, tomoya-sforzando commented on get_amazon.py
> +        """Initialize GetAmazonList."""
```suggestion
        """Initialize AmazonGetter."""
```

2020-11-17 03:34 UTC, tomoya-sforzando commented on get_amazon.py
> +            products (list): List of Amazon items.
コード上では`product_list`を返しているので、変数名に気をつけた方が良い
30行目は、`response = `としておいて、返したい35行目のを `products` とするなど。

2020-11-17 03:34 UTC, tomoya-sforzando commented on tests/test_get_amazon.py
> +    amazon_search_title = AmazonGetter().get_search_list("Alexa")
AmazonGetterのインスタンス化はfixtureでまとめて、1回だけで良い気がします

2020-11-17 04:52 UTC, yusuke-sforzando commented on get_amazon.py
> +            products (list): List of Amazon items.
承知しました。

2020-11-17 04:52 UTC, yusuke-sforzando commented on tests/test_get_amazon.py
> +    amazon_search_title = AmazonGetter().get_search_list("Alexa")
そうですね、そうします。

2020-11-17 06:31 UTC, tomoya-sforzando reviewed
命名についてのコメントを付けたので、一度検討してみてもらえますでしょうか。

2020-11-17 06:31 UTC, tomoya-sforzando commented on get_amazon.py
> +    def get_search_list(self, keyword: str, item_count=3):
`get_search_list` は、検索`結果`のリストを返すメソッドだから`get_search_result_list`とか、
もしくは用途として（登録候補となる）アイテム一覧を取得することになるので`get_items`ないし`get_item_list`で引数に`search_keyword`としておくとか。（itemを使っているのは、引数に`item_count`があるから）

で、#4での詳細情報を取得するメソッドは、`get_item_detail(self, asin)`とかになってくるのかなーといった見通し。

2020-11-17 06:31 UTC, tomoya-sforzando commented on tests/test_get_amazon.py
> +from get_amazon import AmazonGetter
`get_amazon`というのが一見メソッド名に見えてしまって混乱します
つまり、ファイル名を`amazon_getter.py`にして、 `from amazon_getter import AmazonGetter`と書けるようにしてみるとちょっとはよくなるでしょうか？

2020-11-18 09:02 UTC, tomoya-sforzando submitted a review, later dismissed
LGTM.

2020-11-19 04:57 UTC, shin-sforzando requested changes

2020-11-19 04:57 UTC, shin-sforzando commented on tests/test_main.py
> +    assert not search_no_exist
このファイルは `test_man.py` 、つまり、 `main.py` に書いてある処理をテストするもの、
なぜ、 `main.py` に記述のない処理をここでテストしているんですか？

2020-11-19 05:10 UTC, shin-sforzando commented
修正コミット送りました、LGTMなのでマージします。

2020-11-19 05:11 UTC, shin-sforzando approved these changes

2020-11-19 05:19 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert not search_no_exist
すいません、別ファイルで分けるべきでした。
修正ありがとうございます。

2020-11-19 09:14 UTC, tomoya-sforzando approved these changes
LGTM.

2020-11-19 09:14 UTC, merged