Register item in Airtable
sforzando/q-lako pull request #23
Opened 2020-11-18 13:58 UTC by yusuke-sforzando

## Describe the PR

To close #7.
Register item in Airtable.

## Screenshots

(T.B.D.)

## Detail of the change

(T.B.D.)

## Anticipated impacts

(T.B.D.)

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D.)

2020-11-19 07:27 UTC, shin-sforzando requested changes

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +import requests
`requests` は外部ライブラリです。

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +# !/usr/bin/env python3
直接実行できない `.py` になぜShebang?

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +        self.airtable_client = Airtable(os.getenv("airtable_base_id"), "q-lako", os.getenv("airtable_api_key"))
`table_name` のハードコードはいただけませんね。

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +        Retruns:
Typo

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +        """Register with Airtable.
なんで18行目は `Register to Airtable` なのに、こっちは `with` なの？

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +        Register to Airtable,taking as an argument a dictionary
`,` の後には半角空白が必要です。（英語の問題）

2020-11-19 07:27 UTC, shin-sforzando commented on requirements.txt
> +airtable-python-wrapper
`requirements.txt` はABC辞書順が推奨です。

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +        else:
except文に対する `else` は不要では？

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +    def register_table(self, airtable_dict: dict):
この `airtable_dict` はどういった辞書が期待されるのか、どこにも書いてないんですが。

2020-11-19 07:27 UTC, shin-sforzando commented on airtable_client.py
> +            return False
どんな `HTTPError` だったか知らなくて良いんですか？

2020-11-19 07:27 UTC, shin-sforzando commented on tests/test_airtable.py
> +    "Asset code": "B08GGGBKRQ",
`Asset code` って何？

2020-11-19 07:27 UTC, shin-sforzando commented on tests/test_airtable.py
> +        "note": "PS5",
`note` って何？

2020-11-19 07:29 UTC, tomoya-sforzando commented on airtable_client.py
> +            airtable_dict (dict): A dictionary with key names and elements corresponding to the Airtable table.
`airtable_dict`にどんなキーと値（タイプ）が入っていたら良いかがわからない。（こちらを確認すれば良いというのはわかるのだけど、、https://airtable.com/appiqcu26B4FfUXIa/api/docs#curl/table:q-lako）

airtable_dictが意図するキーとパラメータを持って引数として渡されているかの判別処理を加えた方が良いだろうか？
もし`Asset code` というキーでなく、`asset_code`とかで渡されたら、新たにasset_codeという別の列が自動生成されて登録されてしまう？それとも登録できない？

→ APIドキュメントでのcurlで実際にやってみたら、
`{"error":{"type":"UNKNOWN_FIELD_NAME","message":"Unknown field name: \"asset_code\""}}`
が返ってくるね。

2020-11-19 07:29 UTC, tomoya-sforzando commented on airtable_client.py
> +            airtable_dict (dict): A dictionary with key names and elements corresponding to the Airtable table.
Airtableの方に用意されていないフィールドが自動生成されてしまうようなことはなく、登録自体ができないでレスポンスが返ってくるようなので、
>airtable_dictが意図するキーとパラメータを持って引数として渡されているかの判別処理を加えた方が良いだろうか？

ではなく、レスポンス結果をちゃんと確認できるようにtry-exceptの方を整えるので良いかな？

2020-11-19 08:58 UTC, yusuke-sforzando commented on airtable_client.py
> +import requests
承知しました。

2020-11-19 08:58 UTC, yusuke-sforzando commented on airtable_client.py
> +# !/usr/bin/env python3
修正します。

2020-11-19 08:59 UTC, yusuke-sforzando commented on airtable_client.py
> +        self.airtable_client = Airtable(os.getenv("airtable_base_id"), "q-lako", os.getenv("airtable_api_key"))
`table_name`を引数にして変更できるようにします。

2020-11-19 08:59 UTC, yusuke-sforzando commented on airtable_client.py
> +        Retruns:
修正します。

2020-11-19 09:03 UTC, yusuke-sforzando commented on airtable_client.py
> +        """Register with Airtable.
`to`に統一します。

2020-11-19 09:03 UTC, yusuke-sforzando commented on airtable_client.py
> +        Register to Airtable,taking as an argument a dictionary
承知しました。

2020-11-19 09:03 UTC, yusuke-sforzando commented on airtable_client.py
> +        else:
そのまま`return`することにします。

2020-11-19 09:04 UTC, yusuke-sforzando commented on airtable_client.py
> +    def register_table(self, airtable_dict: dict):
PRの本文と、辞書の形が正しいか判定するメソッドを別途用意します。

2020-11-19 09:05 UTC, yusuke-sforzando commented on airtable_client.py
> +            return False
知りたいので、エラー内容を返すようにします。

2020-11-19 09:06 UTC, yusuke-sforzando commented on tests/test_airtable.py
> +    "Asset code": "B08GGGBKRQ",
フィールド名でAmazon APIと関連する箇所は全てAmazonに合わせることとします。
この場合は、`Asset code`ではなく、`asin`に変更します。

2020-11-19 09:08 UTC, yusuke-sforzando commented on tests/test_airtable.py
> +        "note": "PS5",
`note`は備考として使うこととします。
用途は、備品登録時にユーザーが商品の情報とは別に入力するものです。

2020-11-19 09:08 UTC, yusuke-sforzando commented on tests/test_airtable.py
> +        ],
そうですね、この形式でないとpostできないのでこういった形になっています。

2020-11-19 09:09 UTC, yusuke-sforzando commented on tests/test_airtable.py
> +        "Default position": "渡邉宅",
修正します。

2020-11-19 09:09 UTC, yusuke-sforzando commented on airtable_client.py
> +    def register_table(self, airtable_dict: dict):
ありがとうございます。修正します。

2020-11-20 06:50 UTC, shin-sforzando commented
> Reference Value

このReferenceは「参考書」などの参考。Exampleが適切なのでは？

2020-11-20 10:00 UTC, tomoya-sforzando reviewed
すでに修正されているものがありますが、コメントバックします

2020-11-20 10:09 UTC, yusuke-sforzando commented
> ここの説明文も、dataclassがAssetになるとわかりやすくなると思いました

対応します！ありがとうございます！

2020-11-20 10:12 UTC, yusuke-sforzando commented
> テストで追加したデータを消すのってどうしますか？
登録成功後に返ってくる値↓で、id として自動的生成されたものがあるけど、それを指定して消したりすると良い？
{'id': 'rec3iXrt70PWnwdTY', 'fields': {'title': 'PlayStation 5 (CFI-1000A01)', … , 'asin': 'B08GGGBKRQ', 'url': 'https://www.amazon.co.jp/ソニー・インタラクティブエンタテインメント-PlayStation-5-CFI-1000A01/dp/B08GGGBKRQ/', 'contributor': 'None', … }, 'createdTime': '2020-11-20T09:51:28.000Z'}

とりあえず当面は手動で消すことにしたいです。
理由は、登録確認等を確認する際に、テストコードで削除まで行ってしまうと確認しづらいと思っているからです。

仮に削除用の関数を用意するとしても、別でIssuesを立ててやろうと思いますが、どうでしょうか？

2020-11-20 10:16 UTC, tomoya-sforzando commented on tests/test_airtable.py
> +    assert airtable_client.register_assets(registerable_assets)
>とりあえず当面は手動で消すことにしたいです。
>理由は、登録確認等を確認する際に、テストコードで削除まで行ってしまうと確認しづらいと思っているからです。
>仮に削除用の関数を用意するとしても、別でIssuesを立ててやろうと思いますが、どうでしょうか？

そういうことであれば、別Issueでやりましょうか。

2020-11-20 10:47 UTC, tomoya-sforzando commented on airtable_client.py
> +class AirTable:
@yusuke-sforzando さん、全て`Assets`に直してくれているけど複数形かな？

2020-11-20 10:50 UTC, yusuke-sforzando commented
> 全てAssetsに直してくれているけど複数形かな？

登録するアイテムは違いますね。修正いたします！

2020-11-20 12:24 UTC, tomoya-sforzando requested changes

2020-11-20 12:24 UTC, tomoya-sforzando commented on airtable_client.py
> +            return
ただ単にreturnされても困るから、一案なのだけど、、
そのままraiseしてしまって、register_asset()を使用したときにこの例外をそのまま受け取るようにしたらどうかな？
つまり、main.pyで以下のように処理する想定。
```Python
try:
    airtable_client.resigter_asset(…)
    …
    return render_template(…)
except Exception():
    flash('Alert message.')
    return redirect(url_for('index'))
```

```suggestion
            raise he
```

2020-11-20 12:24 UTC, tomoya-sforzando commented on airtable_client.py
> +        with key names corresponding to the Airtable table.
鈴木さんがPRで指摘・修正してくれた文章を使って、
`Register a dictionary with the appropriate key and value to Airtable.` という説明文で良いと思います。

2020-11-20 13:43 UTC, yusuke-sforzando reviewed
> > 全てAssetsに直してくれているけど複数形かな？
> 
> 登録するアイテムは違いますね。修正いたします！

2020-11-20 13:43 UTC, yusuke-sforzando commented on __init__.py
> +time_now = datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()
訂正します。
Assetクラスが呼び出された時に時刻を初期化しようと思うのですがどうでしょう？

Airtableの値はAirtableのテーブルを管理するAssetクラスに一任しようと思っています。

2020-11-20 13:55 UTC, tomoya-sforzando commented on __init__.py
> +time_now = datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()
そうですね。

time_nowなんて変数に入れる必要なく、使う時に`datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()`するでいいんじゃない？

それで実際に使う時というのは、main.pyで resister_asset()が実行される直前、`POST /registeration-details` でフォーム内容が送られてきて、そのデータをdataclassの`Asset`にする時だと思っている。

2020-11-20 14:00 UTC, yusuke-sforzando commented on __init__.py
> +time_now = datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()
> time_nowなんて変数に入れる必要なく、使う時にdatetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()するでいいんじゃない？

そうですね。最新のコミットはそうしています！

> それで実際に使う時というのは、main.pyで resister_asset()が実行される直前、POST /registeration-details でフォーム内容が送られてきて、そのデータをdataclassのAssetにする時だと思っている。

こちらも、その認識で間違い無いです。

2020-11-20 14:28 UTC, tomoya-sforzando submitted a review, later dismissed
LGTM.

2020-11-21 08:30 UTC, shin-sforzando requested changes

2020-11-21 08:30 UTC, shin-sforzando commented on .flake8
> +ignore=H301
Hackingを使ってないから、そもそもHから始まるエラーが出ないはずです。

2020-11-21 08:30 UTC, shin-sforzando commented on requirements.txt
> +#Flask-MonitoringDashboard
requirements.txtはABC辞書順が推奨です、って言わなかったっけ？

2020-11-21 08:30 UTC, shin-sforzando commented on .vscode/settings.json
> +    "GGGBKRQ",
これ、なんですか？

2020-11-21 08:30 UTC, shin-sforzando commented on airtable_client.py
> +from __init__ import app, config
Flaskのappにconfig設定を移せば、ConfigParserを他所で使う必要はないはず。

2020-11-21 08:30 UTC, shin-sforzando commented on airtable_client.py
> +            Dictionary data returned from Airtable.
ほんとに？結果見てみた？

2020-11-21 08:30 UTC, shin-sforzando commented on asset.py
> +        self.registered_at = datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()
ここ、ほんとにこんなに冗長な記述しなきゃできませんか？

2020-11-21 08:33 UTC, yusuke-sforzando commented on .flake8
> +ignore=H301
承知しました。
修正します。

2020-11-21 08:33 UTC, yusuke-sforzando commented on requirements.txt
> +#Flask-MonitoringDashboard
おっしゃっていました。
修正します。

2020-11-21 08:35 UTC, yusuke-sforzando commented on .vscode/settings.json
> +    "GGGBKRQ",
テストコード用のasinコードが含まれていたのを消し忘れていました。
消去します。

2020-11-21 08:48 UTC, yusuke-sforzando commented on airtable_client.py
> +from __init__ import app, config
調べてみます。

2020-11-21 09:11 UTC, yusuke-sforzando commented on airtable_client.py
> +from __init__ import app, config
すいません。これの具体的な実装をどうやるのかわかりませんでした。
教えていただけませんでしょうか？

2020-11-21 09:15 UTC, shin-sforzando commented on airtable_client.py
> +from __init__ import app, config
公式ドキュメントに書いてある。(←言われたら恥ずかしいやつ)
https://flask.palletsprojects.com/en/1.1.x/config/

なんなら、`__init__.py` 22行目にも。(←言われたらとても恥ずかしいやつ)

2020-11-21 09:31 UTC, yusuke-sforzando commented on airtable_client.py
> +from __init__ import app, config
わかりました、ありがとうございます。

2020-11-21 09:36 UTC, yusuke-sforzando commented on airtable_client.py
> +            Dictionary data returned from Airtable.
Airtableに登録した辞書が返ってきますね。
修正いたします。

2020-11-21 09:36 UTC, yusuke-sforzando commented on asset.py
> +        self.registered_at = datetime.now(timezone.utc).astimezone(timezone(timedelta(hours=+9))).isoformat()
もう少し、簡単に書ける方法を探してみます。

2020-11-21 15:31 UTC, shin-sforzando requested changes
Airtableの方のfurniture~とかいうview、何？

2020-11-21 15:31 UTC, shin-sforzando commented on .vscode/settings.json
> +    "GGGBKRQ",
消えてなくね？

2020-11-21 15:31 UTC, shin-sforzando commented on __init__.py
> +app.config["TABLE_NAME"] = config.get("DEFAULT", "table_name")
前も同じような指摘したけど、 `table` って、この業界では汎用すぎて語弊があるよ？

2020-11-21 15:31 UTC, shin-sforzando commented on asset.py
> +        self.asset_id = "0"
`asset_id` は `str` なんだよね？
なんで `0` みたいなintっぽいものを仮置きするの？

2020-11-21 15:31 UTC, shin-sforzando commented on tests/test_airtable_client.py
> +
え、なんで異常系のテスト消えてんの？

2020-11-22 06:44 UTC, yusuke-sforzando commented on .vscode/settings.json
> +    "GGGBKRQ",
失礼しました。消去しました。

2020-11-22 06:44 UTC, yusuke-sforzando commented on __init__.py
> +app.config["TABLE_NAME"] = config.get("DEFAULT", "table_name")
そうですね、Airtableのtable名なのでAIRTABLE_TABLE_NAMEにしようと思います。

2020-11-22 06:44 UTC, yusuke-sforzando commented on asset.py
> +        self.asset_id = "0"
そうですね。
登録日時を`str`で表したいので、それに沿った内容にします。

2020-11-22 06:44 UTC, yusuke-sforzando commented on tests/test_airtable_client.py
> +
追加します。

2020-11-22 08:03 UTC, tomoya-sforzando commented on tests/test_airtable_client.py
> +    assert "asset should be called on asset dataclass instances" in airtable_client.register_asset({"test": "test"})
TypEerrorをそのままraiseするのを採用するならば、このようなテストとして書けると思います
```Python
with pytest.raises(TypeError):
    airtable_client.register_asset({"test": "test"})
```

2020-11-22 08:06 UTC, yusuke-sforzando commented on airtable_client.py
> +            return "asset should be called on asset dataclass instances"
そうですね。
今やってみましたが、こちらの方が綺麗なので修正します。
ありがとうございます。

2020-11-22 13:03 UTC, tomoya-sforzando commented on asset.py
> +        self.asset_id = datetime.now(timezone(timedelta(hours=9))).isoformat(timespec="seconds")
Airtableの方で確認してきたのですが、idに記号が混じってるのが気持ち悪いので、UNIX時間を使うのではどうでしょうか？
roundしているのは、小数点以下を削って、`1606049967` の数字の羅列にしたいためです。
```Python
now = datetime.now(timezone(timedelta(hours=9)))
self.asset_id = round(datetime.timestamp(now))
self.registered_at = now.isoformat()
```

2020-11-22 13:03 UTC, tomoya-sforzando commented on asset.py
> +        self.asset_id = datetime.now(timezone(timedelta(hours=9))).isoformat(timespec="seconds")
とすると、 `asset_id` は `int` でもよいかもですね。

2020-11-22 13:05 UTC, shin-sforzando requested changes

2020-11-22 13:05 UTC, shin-sforzando commented on .vscode/settings.json
> +    "qlako",
`qlako` ってスペルミスじゃないの？

2020-11-22 13:05 UTC, shin-sforzando commented on tests/test_airtable_client.py
> +    return airtable_client
`asset_id` や `registered_at` が正しく設定されてるか確認しないと。

2020-11-22 13:11 UTC, yusuke-sforzando commented on asset.py
> +        self.asset_id = datetime.now(timezone(timedelta(hours=9))).isoformat(timespec="seconds")
いいですね！
確かに、IDは一意であればよいので、UNIX時間を使うと衝突の心配もなさそうです。
`int`で修正します！

2020-11-22 13:11 UTC, yusuke-sforzando commented on .vscode/settings.json
> +    "qlako",
そうですね。
修正します！

2020-11-22 13:12 UTC, yusuke-sforzando commented on tests/test_airtable_client.py
> +    return airtable_client
そうですね、テストコードを追記します。

2020-11-23 05:39 UTC, tomoya-sforzando commented on asset.py
> +    asset_id: str = field(init=False)
```suggestion
    asset_id: int = field(init=False)
```

2020-11-23 07:30 UTC, shin-sforzando approved these changes

2020-11-23 08:21 UTC, tomoya-sforzando approved these changes
鈴木さん、調整ありがとうございます。確認しました。

2020-11-23 08:22 UTC, merged