Create input form
sforzando/q-lako pull request #26
Opened 2020-11-20 11:41 UTC by yusuke-sforzando

## Describe the PR

To close #9 .
Create input form.

## Screenshots

(T.B.D.)

## Detail of the change

(T.B.D.)

## Anticipated impacts

(T.B.D.)

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D.)

2020-11-21 04:55 UTC, tomoya-sforzando commented on main.py
> +@app.route("/", methods=["GET", "POST"])
現仕様で、POSTリクエストを受け取る見込みはありません。

2020-11-21 04:55 UTC, tomoya-sforzando commented on main.py
> +        "sub_title": "キーワード、ISBNコード、ASINコードのいずれかを入力してください"
現状、Index.htmlで可変な文字列などを扱いたい要素がないので、context_dictは不要で、
titleとかsubtitleなどは、index.htmlの方にベタがきで良いです。

2020-11-21 04:55 UTC, tomoya-sforzando commented on main.py
> +    session["keyword"] = request.form.get("input_keyword")
不要です。

2020-11-21 04:55 UTC, tomoya-sforzando commented on templates/index.html
> +<form action="/" method="POST">
```suggestion
<form action="/search-result" method="GET">
```

2020-11-21 04:55 UTC, tomoya-sforzando commented on main.py
> +    }
GETリクエストからのデータを取得するのは、`keyword = request.args.get('input_keyword', '')` でいけないかな？
cf. [Quickstart — Flask Documentation (1.1.x)](https://flask.palletsprojects.com/en/1.1.x/quickstart/#accessing-request-data)

2020-11-21 04:55 UTC, tomoya-sforzando commented on templates/index.html
> +<p>{{ sub_title }}</p>
titleとsub_titleはベタ書きで良いです

2020-11-21 04:55 UTC, tomoya-sforzando commented on templates/index.html
> +  <button type="submit" value="検索">検索</button>
```suggestion
  <input type="submit" value="検索" />
```

2020-11-21 04:55 UTC, tomoya-sforzando commented on templates/search-result.html
> +<p>{{ title }}</p>
titleはベタ書きで良いです

2020-11-21 06:15 UTC, yusuke-sforzando commented on main.py
> +@app.route("/", methods=["GET", "POST"])
承知しました！

2020-11-21 06:15 UTC, yusuke-sforzando commented on main.py
> +        "sub_title": "キーワード、ISBNコード、ASINコードのいずれかを入力してください"
そうですね、ベタ書きでいきます！

2020-11-21 06:17 UTC, yusuke-sforzando commented on main.py
> +    }
検証してみます！

2020-11-21 06:27 UTC, yusuke-sforzando commented on main.py
> +    }
問題なさそうなので
`keyword = request.args.get('input_keyword', '')`でいきます！

2020-11-21 07:48 UTC, tomoya-sforzando requested changes

2020-11-21 07:48 UTC, tomoya-sforzando commented on main.py
> +@app.route("/", methods=["GET", "POST"])
POSTリクエストを受けつける見込みはないので、POSTを削除してください

2020-11-21 07:48 UTC, tomoya-sforzando commented on main.py
> +    return "TOPページに戻ってキーワードを入力してください"
20行目以降の `@app.route("/search-result", methods=["GET"])` 内で、argumentに`input_keyword`とその値を持っているかどうかの判別をして、その結果としてmessageを表示するようにして欲しいです

ので、`search_result_direct_access():`は不要です

2020-11-21 07:48 UTC, tomoya-sforzando commented on main.py
> +        return render_template("search-result.html", keyword=keyword)
元あった `context_dict` を活かして、`keyword` を追加する方が良いかな。
なぜなら、この後`context_dict`には、Amazon  PA-APIで取得した結果とか、default_positionsとかそう言うのが追加されていくことが想定できるから。

2020-11-21 07:48 UTC, tomoya-sforzando commented on main.py
> +        return "TOPページに戻ってキーワードを入力してください"
この文字列は、元あった`context_dict`の`message`に追加すれば良いかな。

2020-11-21 07:48 UTC, tomoya-sforzando commented on templates/index.html
> +<label>キーワード、ISBNコード、ASINコードのいずれかを入力してください</label>
`label` は `input` タグに対応させるものなので、以下のような並びと書き方になるかと。
cf. https://developer.mozilla.org/ja/docs/Web/HTML/Element/label
```html
<label for="input_keyword">キーワード、ISBNコード、ASINコードのいずれかを入力してください</label>
<input type="text" name="input_keyword" id="input_keyword" placeholder="PlayStation 5">
```

2020-11-21 07:53 UTC, yusuke-sforzando commented on main.py
> +    return "TOPページに戻ってキーワードを入力してください"
すでにそういう実装になっていましたね...
修正します。

2020-11-21 07:53 UTC, yusuke-sforzando commented on main.py
> +        return render_template("search-result.html", keyword=keyword)
確かにそうですね。
修正します。

2020-11-21 08:12 UTC, tomoya-sforzando commented on main.py
> +        "message": "TOPページに戻ってキーワードを入力してください"
この`mesage`に`"TOPページに戻ってキーワードを入力してください"`を付与するかどうかは、`input_keyword`の有無で判断させてください

2020-11-21 08:12 UTC, tomoya-sforzando commented on main.py
> +        "keyword": request.args.get("input_keyword", ""),
17行目があるので、これで良いはず
```suggestion
        "keyword": keyword,
```

2020-11-21 08:12 UTC, tomoya-sforzando commented on main.py
> +        return context_dict["message"]
こんな感じで
```Python
if not keyword:
   context_dict["message"] = "…"

return render_template("search-result.html", **context_dict)
```

2020-11-21 08:12 UTC, tomoya-sforzando commented on templates/index.html
> +  <input type="text" name="input_keyword" placeholder="PlayStation 5">
この直前に、`<label>` を配置してください
labelとinputでペアです

2020-11-21 08:29 UTC, tomoya-sforzando commented on main.py
> +        return render_template("search-result.html", **context_dict)
https://github.com/sforzando/q-lako/pull/26#discussion_r528150356

`return render_template("search-result.html", **context_dict)` を2つ書いているの無駄くない？

2020-11-21 08:31 UTC, tomoya-sforzando commented on templates/index.html
> +    <input type="text" name="input_keyword" placeholder="PlayStation 5">
```suggestion
    <input type="text" name="input_keyword" placeholder="PlayStation 5" />
```

2020-11-21 09:09 UTC, shin-sforzando requested changes
`.env.gpg` に変更があるようですが、どのような変更ですか？

2020-11-21 09:09 UTC, shin-sforzando commented on tests/test_main.py
> +    assert "書籍・備品の登録", "キーワード、ISBNコード、ASINコードのいずれかを入力してください" in response.data.decode('utf-8')
この `,` って何？

2020-11-21 09:09 UTC, shin-sforzando commented on templates/search-result.html
> +{% extends "_base.html" %}
このファイル、 `search.html` じゃダメなの？

2020-11-21 09:09 UTC, shin-sforzando commented on tests/test_main.py
> +    print(response.data)
このprint文、標準出力に出ないから無駄。

2020-11-21 09:09 UTC, shin-sforzando commented on tests/test_main.py
> +    assert b"kindle" not in response.data
32行目のように判定すべきでは？

2020-11-21 09:09 UTC, shin-sforzando commented on tests/test_main.py
> +def test_GET_search_result_direct_access(test_client):
このテスト、何がしたいの？

2020-11-21 09:15 UTC, yusuke-sforzando commented
> .env.gpg に変更があるようですが、どのような変更ですか？

Flaskのsessionを使おうとしていた時に試験的にシークレットキー追記していました。
sessionが不要とのことで、元に戻してあります。

よって今までの.gpgファイルと変わりはありません。
紛らわしいことをして申し訳ありません。

2020-11-21 09:20 UTC, tomoya-sforzando commented on tests/test_main.py
> +def test_GET_search_result_direct_access(test_client):
`test_GET_search_result_query_not_inputted(test_client):`とまったく一緒になってしまっていますね。ミスです。
36行目で、`response = test_client.get("/search-result")` として、検索キーワードが空白でリクエストされた時と、直接クエリなしでリクエストされた時とので、同じメッセージが表示されることをテストしたいものでした。

2020-11-21 09:25 UTC, tomoya-sforzando commented on tests/test_main.py
> +    print(response.data)
削除し忘れでした。修正します

2020-11-21 09:27 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert b"kindle" not in response.data
確かに、予期せぬクエリでリクエストされた時にも、表示メッセージとしては"TOPページに戻ってキーワードを入力してください"ですね。すでに、main.pyの処理がそのようにできているので、テストを修正します。

2020-11-21 09:29 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert "書籍・備品の登録", "キーワード、ISBNコード、ASINコードのいずれかを入力してください" in response.data.decode('utf-8')
`書籍・備品の登録` と `キーワード、ISBNコード、ASINコードのいずれかを入力してください` の2つの文字列があるかをテストしています

2020-11-21 09:32 UTC, tomoya-sforzando commented on main.py
> +    keyword = request.args.get("input_keyword", "")
@yusuke-sforzando さん、`query` にしましょう。testの方は修正しておきます

2020-11-21 09:35 UTC, tomoya-sforzando commented on templates/search-result.html
> +{% extends "_base.html" %}
@yusuke-sforzando さん、こちらも `search.html` に修正しましょう
GET リクエストされた時も `/search?query=kindle`と言うような形になって見なれたものになるので、良いと思います。

2020-11-21 10:23 UTC, shin-sforzando commented on tests/test_main.py
> +    assert "書籍・備品の登録", "キーワード、ISBNコード、ASINコードのいずれかを入力してください" in response.data.decode('utf-8')
もし片方しかなかったらどうなるの？

2020-11-21 10:25 UTC, yusuke-sforzando commented on templates/search-result.html
> +{% extends "_base.html" %}
承知しました。

2020-11-21 10:30 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert "書籍・備品の登録", "キーワード、ISBNコード、ASINコードのいずれかを入力してください" in response.data.decode('utf-8')
あ、片方なくても通っちゃいますね。すみません。不完全なテストでした。修正します。

2020-11-23 13:09 UTC, tomoya-sforzando commented on main.py
> +@app.route("/search", methods=["GET", "POST"])
`search`に関しては、 `GET`で良いと思うんですよね。。

2020-11-23 13:13 UTC, yusuke-sforzando commented on main.py
> +@app.route("/search", methods=["GET", "POST"])
承知しました。
修正します。

2020-11-23 13:41 UTC, tomoya-sforzando requested changes

2020-11-23 13:41 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /search")
```suggestion
    app.logger.info(f"search(): GET {request.full_path}")
```
こうすると、queryも込みでlogger出力してくれます

2020-11-23 13:41 UTC, tomoya-sforzando commented on main.py
> +    return render_template("search.html", **context_dict)
```suggestion
    return render_template(template_filename, **context_dict)
```
としておきましょうか。

2020-11-23 13:41 UTC, tomoya-sforzando commented on templates/search.html
> +{% endif %}
僕の考えではなのですが、messageはflash messageとして使う予定で、それはどのテンプレートでも共通してmessageがあれば表示するということを考えていたので、`_base.html`に書いてあると良いかなと思っています。
どうでしょうか？

2020-11-23 13:41 UTC, tomoya-sforzando commented on templates/index.html
> +    <p>キーワード、ISBNコード、ASINコードのいずれかを入力してください</p>
```suggestion
    <label for="query">キーワード、ISBNコード、ASINコードのいずれかを入力してください</label>
```

2020-11-23 13:41 UTC, tomoya-sforzando commented on templates/index.html
> +    <input type="text" name="query" placeholder="サーカスTC">
```suggestion
    <input type="text" name="query" id="query" placeholder="サーカスTC">
```

2020-11-23 13:41 UTC, tomoya-sforzando commented on tests/test_main.py
> +    response = test_client.get("search?query=")
```suggestion
    response = test_client.get("/search?query=")
```

2020-11-23 13:54 UTC, yusuke-sforzando commented on templates/search.html
> +{% endif %}
そうですね。
全ページにエラーページのようなものが必要そうですし、面倒なので_base.htmlに入れちゃうのはアリだと思います。
やってみます。

2020-11-23 13:55 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): GET /search")
ありがとうございます。

2020-11-23 14:30 UTC, tomoya-sforzando commented on main.py
>          "subtitle": template_filename,
subtitleって`search.html`で使ってないみたいなので、不要ですね。
とすると、`template_filename` を用意する必要もなさそうですね。

2020-11-23 14:32 UTC, tomoya-sforzando commented on main.py
>      return render_template(template_filename, **context_dict)
```suggestion
    return render_template("search.html", **context_dict)
```
行ったりきたりですが、、

2020-11-23 14:33 UTC, yusuke-sforzando commented on main.py
>          "subtitle": template_filename,
承知しました。
修正します！

2020-11-23 14:40 UTC, yusuke-sforzando commented on main.py
>          "subtitle": template_filename,
と、思ったのですが、`_base.html`で使っていると思うのですが違いますか？
`  <title>q-lako - {{ subtitle | default("a service to quickly register equipments and books") }}</title>`
で、使っていると思うのですが...

2020-11-23 15:06 UTC, tomoya-sforzando commented on main.py
>          "subtitle": template_filename,
僕の見落としです。使っていますね。すみません。

2020-11-23 15:08 UTC, tomoya-sforzando commented on main.py
>          "subtitle": template_filename,
でも、subtilteが`search.html`ってのもおかしいので、適切な感じで直しておきましょうか。

2020-11-23 15:15 UTC, yusuke-sforzando commented on main.py
>          "subtitle": template_filename,
承知しました！

2020-11-23 15:24 UTC, tomoya-sforzando commented on main.py
> +    template_filename = "search.html"
1箇所でしか使ってないので、変数でなくて良いかと。

2020-11-23 15:26 UTC, tomoya-sforzando commented on main.py
> +        "subtitle": "product list",
`<h1>検索結果</h1>`と`search.html`で書いてあるので、`search result`で良いかな。（これはアンチパターンでないよね。汗）

2020-11-23 15:28 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": "product list",
修正しました！ありがとうございます！

2020-11-23 15:29 UTC, tomoya-sforzando commented on templates/index.html
> +    <input type="text" name="query" id="query" placeholder="サーカスTC">
```suggestion
    <input type="text" name="query" id="query" placeholder="サーカスTC" />
```

2020-11-23 15:34 UTC, tomoya-sforzando approved these changes, later dismissed
LGTM.

2020-11-25 06:54 UTC, shin-sforzando requested changes
`query` が指定されなかった時の表示、こんなんで良いわけないですよね。

<img width="515" alt="Screen Shot 2020-11-25 at 15 46 42" src="https://user-images.githubusercontent.com/32637762/100193030-5ffba980-2f36-11eb-8d42-a2a6cb6c0550.png">

2020-11-25 07:05 UTC, yusuke-sforzando commented
> `query` が指定されなかった時の表示、こんなんで良いわけないですよね。
> 
> <img alt="Screen Shot 2020-11-25 at 15 46 42" width="515" src="https://user-images.githubusercontent.com/32637762/100193030-5ffba980-2f36-11eb-8d42-a2a6cb6c0550.png">

2020-11-25 07:05 UTC, yusuke-sforzando commented
失礼しました。
修正します。

2020-11-25 08:04 UTC, tomoya-sforzando commented on templates/search.html
> +  <h2>Keyword: {{ keyword }}</h2>
Flash messageを実装したらそもそもTopページにリダイレクトさせてからのメッセージ表示とかにできたらと思っているのだけど、

現時点では、messageが表示される = Keyword がない というない状況で、`keyword: `と表示されているのは変だから、
```html
{% if not message %}
<h2>Keyword: {{ keyword }}</h2>
{% endif %}
```
の場合分けをするのはどうでしょうか？

2020-11-25 08:10 UTC, yusuke-sforzando commented on templates/search.html
> +  <h2>Keyword: {{ keyword }}</h2>
そうですね。その方が良いですね。
修正します。

2020-11-25 14:15 UTC, shin-sforzando commented on templates/search.html
> +  <h2>Keyword: {{ keyword }}</h2>
いや、むしろ `index.html` に戻してあげなよ。message付きで。

2020-11-25 14:18 UTC, yusuke-sforzando commented on templates/search.html
> +  <h2>Keyword: {{ keyword }}</h2>
なるほどですね。
そうですね、そちらの方がユーザーファーストなのでそちらでやってみます。

2020-11-26 05:48 UTC, tomoya-sforzando commented on main.py
> +        "message": None if keyword else "Enter keywords back on the top page."
`index.html`で表示されるメッセージなら、文章としては、`"Enter any keywords."` で良さそうですね

2020-11-26 05:49 UTC, tomoya-sforzando commented on main.py
> +app.secret_key = "aasss"
このPRでは、不要と思います。

2020-11-26 05:50 UTC, yusuke-sforzando commented on main.py
> +        "message": None if keyword else "Enter keywords back on the top page."
そうですね。
修正します。

2020-11-26 05:50 UTC, yusuke-sforzando commented on main.py
> +app.secret_key = "aasss"
そうですね、修正します。

2020-11-26 06:53 UTC, shin-sforzando requested changes

2020-11-26 06:53 UTC, shin-sforzando commented on main.py
> +        return render_template("index.html", **context_dict)
これでは `index.html` の `title` が `Search Result for ` になります。

2020-11-26 06:53 UTC, shin-sforzando commented on templates/index.html
> +    <label for="query">Enter one of the following keywords: keyword, ISBN code, or ASIN code </label>
英文なんだから末尾にピリオドが要りますよね。

2020-11-26 06:53 UTC, shin-sforzando commented on templates/search.html
> +  <h2>Keyword: {{ keyword }}</h2>
`index.html` がレンダーされた、と言うテストが必要なのでは？

2020-11-26 06:57 UTC, yusuke-sforzando commented on main.py
> +        return render_template("index.html", **context_dict)
そうですね。
`context_dict`の`subtitle`を変更するコードを追記します。

2020-11-26 06:57 UTC, yusuke-sforzando commented on templates/index.html
> +    <label for="query">Enter one of the following keywords: keyword, ISBN code, or ASIN code </label>
失礼しました。追記します。

2020-11-26 08:06 UTC, shin-sforzando requested changes

2020-11-26 08:07 UTC, yusuke-sforzando commented on main.py
>      context_dict = {
なるほどですね。
承知しました、修正します！

2020-11-26 08:07 UTC, yusuke-sforzando commented on main.py
> +        context_dict["subtitle"] = "a service to quickly register equipments and books."
承知しました！修正します！

2020-11-26 08:16 UTC, shin-sforzando approved these changes

2020-11-26 08:37 UTC, tomoya-sforzando approved these changes
確認しました

2020-11-26 08:38 UTC, merged