Implement flask for Simple HTML Page
sforzando/q-lako pull request #27
Opened 2020-10-07 06:34 UTC by yusuke-sforzando

## Describe the PR

To close #24 
Implement Flask.

## Screenshots

`http://localhost:5000`
<img width="677" alt="Screen Shot 2020-10-07 at 15 21 26" src="https://user-images.githubusercontent.com/67737076/95294748-c8bc9300-08b0-11eb-83f1-f91b15f5ea53.png">

## Detail of the change

Create a simple HTML page with Flask.
Displayed `Hello World` on the web browser.

## To reproduce

Steps to check the behavior:

1. Update Libraries  
```shell 
pip install -r requirements.txt`
```
2. Run `python src/main.py`
3. Search for `http://localhost:5000`

2020-10-07 07:03 UTC, tomoya-sforzando reviewed
いくつかコメントを付けましたので、確認お願いします。

2020-10-07 07:03 UTC, tomoya-sforzando commented on requirements.txt
> +flask
flake8も必要？

2020-10-07 07:03 UTC, tomoya-sforzando commented on test.http
> +http://127.0.0.1:5000/
このファイルって何かわからないのですが、教えてもらえますでしょうか。

2020-10-07 07:27 UTC, shin-sforzando requested changes

2020-10-07 07:27 UTC, shin-sforzando commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/venv,osx,vscode,linux,node
既に1-43行目で `linux` と `osx` についての記述があるため、重複しています。

2020-10-07 07:27 UTC, shin-sforzando commented on README.md
> +`Shell`
`Shell` とか要らないです。

2020-10-07 07:27 UTC, shin-sforzando commented on src/main.py
> +from flask import Flask
なんで `src/` の下に置いているんだろう。
`src` とはコンパイル元だから `source` なわけで、この `main.py` はコンパイルされるんだろうか。

2020-10-07 09:17 UTC, yusuke-sforzando commented on .editorconfig
> -# editorconfig.org
わかりました。付け加えます。

2020-10-07 09:19 UTC, yusuke-sforzando commented on requirements.txt
> +flask
変更しました。

2020-10-07 09:26 UTC, yusuke-sforzando commented on test.http
> +http://127.0.0.1:5000/
このファイルは、VS Code上でHTTPのレスポンスが調べられる
詳しくはこちらを参考にしました。
https://qiita.com/toshi0607/items/c4440d3fbfa72eac840c

2020-10-07 09:31 UTC, tomoya-sforzando commented on test.http
> +http://127.0.0.1:5000/
そのVS Codeの拡張を使っての開発自体を共有するということなら、README.mdにその旨を書いた方が良いですね。
そうでなく、自身が便利に使うというレベルで止めるなら、このファイルの共有は不要だと思います。

2020-10-07 09:47 UTC, yusuke-sforzando commented on test.http
> +http://127.0.0.1:5000/
私がフロントのことを知らなさ過ぎるので、チェック用で使いたいな、と思って入れてあります。

2020-10-07 09:48 UTC, shin-sforzando commented
そもそも、HTTPレスポンスは返してるけどHTMLページは返してなくない？

2020-10-07 09:50 UTC, yusuke-sforzando commented on README.md
> +`Shell`
わかりました。

2020-10-07 09:52 UTC, yusuke-sforzando commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/venv,osx,vscode,linux,node
削除しました。

2020-10-07 09:53 UTC, yusuke-sforzando commented on test.http
> +http://127.0.0.1:5000/
承知しました。
自分レベルに止めるので削除します。

2020-10-07 09:55 UTC, yusuke-sforzando commented on src/main.py
> +from flask import Flask
コンパイルされないので、ファイルの構造を変更します。

2020-10-07 10:06 UTC, yusuke-sforzando commented
@tomoya-sforzando さん
先ほど、鈴木さんにご指摘頂いたので、
FlaskにおけるWebページの雛形に沿ってファイル構成を作り替えます。

2020-10-07 10:47 UTC, yusuke-sforzando commented
`http://localhost:8888`に変更してあります。
こちらで確かめてください。よろしくお願いします。

2020-10-07 11:19 UTC, shin-sforzando requested changes

2020-10-07 11:19 UTC, shin-sforzando commented on .gitignore
> +### Node ###
もうNodeも削除して良いのでは？

2020-10-07 11:19 UTC, shin-sforzando commented on README.md
> +pip install -r requirements.txt
この章に書くということは実行するたびに毎回依存ライブラリをインストールしろってことだよ？

2020-10-07 11:19 UTC, shin-sforzando commented on main.py
> +    app.run(debug=True, host='0.0.0.0', port=8888, threaded=True)
`threaded=True` がどういう意味を持つかわかって書いてますよね？

2020-10-07 11:19 UTC, shin-sforzando commented on requirements.txt
> +flask
Fは大文字って言ったんだが？

2020-10-07 11:21 UTC, yusuke-sforzando commented on .gitignore
> +### Node ###
そうですね、削除します。

2020-10-07 11:22 UTC, tomoya-sforzando reviewed
VS Codeのsettings.jsonに合わせて、requirements.txtに`autopep8`を追記しました。
Format documentsを実行し、mainpage.htmlを整形しました。

2020-10-07 11:22 UTC, tomoya-sforzando commented on README.md
> +I think you can check the `this is main page`  on your browser..
ここの2文はいらないかな。実行すれば、コンソールにURLとか表示されるので。

2020-10-07 11:29 UTC, yusuke-sforzando commented on main.py
> +    app.run(debug=True, host='0.0.0.0', port=8888, threaded=True)
並列処理を可能としている、と書いてあったので入れています。
並列処理はできた方がいいと思っていました。

2020-10-07 11:30 UTC, yusuke-sforzando commented on README.md
> +pip install -r requirements.txt
そうですね。
別の章の最初の手順として書くべきでした。
訂正します。

2020-10-07 11:30 UTC, yusuke-sforzando commented on requirements.txt
> +flask
すいませんでした。
修正します。

2020-10-07 11:31 UTC, yusuke-sforzando commented on README.md
> +I think you can check the `this is main page`  on your browser..
承知しました。削除します。

2020-10-07 11:56 UTC, tomoya-sforzando approved these changes

2020-10-07 14:22 UTC, shin-sforzando commented on main.py
> +@app.route("/", methods=["GET", "POST"])
POSTに対してもこのHTMLを返して良いの？

2020-10-07 14:22 UTC, shin-sforzando commented on main.py
> +    app.run(debug=True, host='0.0.0.0', port=8888, threaded=True)
書いた結果としては間違ってないけど、その意味がわかってないなら危険だな。
小田原でも言ったように「自分が説明できないコードは書くな」、守れてると言える？

2020-10-07 14:24 UTC, shin-sforzando requested changes

2020-10-07 14:24 UTC, shin-sforzando commented on templates/mainpage.html
> +<!DOCTYPE html>
`/main` というURLに対して `mainpage.html` というように対応をわかりやすく命名してください。

2020-10-07 14:27 UTC, shin-sforzando commented on main.py
> +    app.run(debug=True, host='0.0.0.0', port=8888, threaded=True)
俺たちよりも遥かに頭の良い人たちが、わずか1行で有効にできるマルチスレッドまで実装しておいて、defaultでは無効にしているのはなぜだろうか？

2020-10-07 14:35 UTC, yusuke-sforzando commented on main.py
> +@app.route("/", methods=["GET", "POST"])
これは二つの場合に分けて処理を変えないといけないと言うことですよね。
 ダメですね。
最初のFlaskでHTMLページを返すと言う状況においてはGETだけで良いと思いますので、POSTの記述は削除しようと思います。

2020-10-07 14:36 UTC, yusuke-sforzando commented
> 書いた結果としては間違ってないけど、その意味がわかってないなら危険だな。
小田原でも言ったように「自分が説明できないコードは書くな」、守れてると言える？

言えません。正しく理解していないのに必要だろうと入れてしまったのはダメでした。
もう一度調べてきます。

2020-10-07 15:07 UTC, shin-sforzando requested changes

2020-10-07 15:07 UTC, shin-sforzando commented on main.py
> +    return render_template("mainpage.html")
```suggestion
def index():
    return render_template("index.html")
```

2020-10-07 16:35 UTC, shin-sforzando approved these changes

2020-10-07 16:36 UTC, merged

2020-11-24 08:01 UTC, yusuke-sforzando commented on main.py
> +    product_list = amazon_api_client.search_products(keywords=keyword)
承知しました！

2020-11-24 10:10 UTC, shin-sforzando commented on tests/test_main.py
> +    assert response.data.decode("utf-8").count("サーカスTC") > 1
等号不等号の向きは左側が小です。
ちなみに、検索結果が一つしかない場合は考慮しないんですか？

```suggestion
    assert 1 <= response.data.decode("utf-8").count("サーカスTC")
```

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +            raise ae
ここではもうraiseするのではなく、ユーザーにエラーを伝えてほしいです

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info(f"search(): GET /{request.full_path}")
`{request.full_path}` だけで、`/search?query=kindle` 的に出力します
```suggestion
    app.logger.info(f"search(): GET {request.full_path}") 
```