List the search result with Amazon API
sforzando/q-lako pull request #27
Opened 2020-11-21 07:47 UTC by yusuke-sforzando

## Describe the PR

To close #11 .
List the search result with Amazon API.

## Screenshots

(T.B.D.)

## Detail of the change

A clear and concise description of what you changed.

## Anticipated impacts

A clear and concise description of where may be affected by the changes.

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D.)

2020-11-22 08:41 UTC, tomoya-sforzando commented on templates/search.html
> +      </label>
> label の中にアンカーやボタンのような対話型要素を配置しないでください。
cf. [<label> - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/label)

と言うことなので、`label` で囲う記述もなしではないのですが、ここでは不適切かな。

2020-11-22 08:41 UTC, tomoya-sforzando commented on main.py
> +    return render_template("search.html", keyword=keyword, products_list=products_list)
`render_template`に渡すデータは、 `context_dict` に集約する方針でいきませんか？

2020-11-22 08:41 UTC, tomoya-sforzando commented on main.py
> +    keyword = "サーカスTC"
```suggestion
    keyword = request.args.get("query", "")
```
と、requestのクエリを受け取ってください（PR#26 でやっている内容です）

2020-11-22 08:41 UTC, tomoya-sforzando commented on templates/search.html
> +  <image src="{{ product.image_url }}" />
```suggestion
  <image src="{{ product.image_url }}" alt="image of {{ product.title }}" />
```
と言う感じで、`alt` を追加しておきましょう

2020-11-22 08:45 UTC, yusuke-sforzando commented on templates/search.html
> +      </label>
承知しました。
今回は`label`を修正します。

2020-11-22 08:45 UTC, yusuke-sforzando commented on main.py
> +    return render_template("search.html", keyword=keyword, products_list=products_list)
承知しました。
その方が見やすいのでそうします。

2020-11-22 08:46 UTC, yusuke-sforzando commented on main.py
> +    keyword = "サーカスTC"
承知しました。
#26 の内容をそのまま使います。

2020-11-22 08:46 UTC, yusuke-sforzando commented on templates/search.html
> +  <image src="{{ product.image_url }}" />
承知しました。
修正します。

2020-11-22 13:15 UTC, shin-sforzando requested changes

2020-11-22 13:15 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /search")
logにどんなqueryで呼ばれたか書き込んだら良いのに。

2020-11-22 13:15 UTC, shin-sforzando commented on main.py
> +@app.route("/registration-details", methods=["GET"])
これ、 `registration` じゃダメなの？

2020-11-22 13:15 UTC, shin-sforzando commented on main.py
> +        products_list.append({"asin": product.asin, "title": product.title, "image_url": product.images.large})
なんか冗長だなぁ。

2020-11-22 13:15 UTC, shin-sforzando commented on templates/search.html
> +<label>
`<label>` の使い方おかしい。

2020-11-22 13:15 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
registration操作はPOSTでしょ。
RESTについて調べなおして。

2020-11-22 13:32 UTC, yusuke-sforzando commented on main.py
> +@app.route("/registration-details", methods=["GET"])
問題ありません。
registrationに修正します。

2020-11-22 13:32 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): GET /search")
そうします。
ありがとうございます。

2020-11-22 13:36 UTC, yusuke-sforzando commented on main.py
> +        products_list.append({"asin": product.asin, "title": product.title, "image_url": product.images.large})
こちらはもうリストの形のsearch_products_resultで持って、viewの方で読み取れるようにしてみます。

2020-11-22 13:36 UTC, yusuke-sforzando commented on templates/search.html
> +<label>
承知しました。調べ直して修正します。

2020-11-22 13:36 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
承知しました。

2020-11-22 13:43 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
@shin-sforzando さん、
`/search` からの一つ選択で、 `GET /registration` の編集状態になって、そのページのsubmitボタンで `POST /registration` を想定していたのですが、おかしいです？

2020-11-22 13:53 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
GETは取得、POSTは挿入、GETは冪等、POSTは不冪等。

2020-11-22 14:12 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
Indexにて、任意のキーワード入力で検索 → `GET /search?q=kindle` 
→ 一覧ページが表示される → そのうちの一つを選択する → `GET /registration?asin=B07HCSQ48P` 
→ amazon pa-apiで取得したkindleの情報が編集できる状態で表示される → 編集したデータを伴って `POST /registration` 

`GET /registration?asin=B07HCSQ48P` なら冪等性が保てれているといえないでしょうか？
そもそもルーティングとかでおかしい？

2020-11-22 14:19 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
そのasinでもう一回Amazon API呼ぶの？

2020-11-22 14:24 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
>そのasinでもう一回Amazon API呼ぶの？
これは、実はそのつもりなんですよね。というのは、無駄にリクエストすることは承知の上で、cookieとかsessionとか、時間ない現状であれこれコーディング頑張ってもらうより、シンプルな実装で時間短縮を狙って。

2020-11-22 15:07 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
え、session/cookie使うかとは関係なくAPI呼び出しは一回で実装できるじゃん。

2020-11-22 15:54 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
あれ？僕、なんかとんでもない勘違いしてる？
searchする時にAPI使って、そのデータを使って`/search`で一覧を描画して、そこでユーザーがどれかを選択してリクエストしちゃうと、もうサーバー側ではAPIで取得したデータって保持できてないよね？あれ？あれ？

2020-11-22 16:10 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
`<input type="hidden" name="asin" ~>` ってやってて気づかないの？

2020-11-22 16:11 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
または、普通にsession使う方が筋は良いけどね。

2020-11-22 16:51 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
ふーむ、ひとりが実行している限りは大丈夫ってことか。複数人がってなると、普通にsessionになりますね。
ログインとか無くして機能としてミニマムでって進んでるから、
> session/cookie使うかとは関係なくAPI呼び出しは一回で実装できるじゃん。

の路線で進みたいですね。ひとりで混乱してすみません。

2020-11-22 17:16 UTC, tomoya-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
@yusuke-sforzando さん、
鈴木さんの指摘点から脱線させてしまってすみません。
`POST /registration` で詳細編集ページへ遷移して、そこからの登録ボタンで、`POST /result`とかそういった感じになるかと思います。

2020-11-22 20:12 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
> ふーむ、ひとりが実行している限りは大丈夫ってことか。

???

2020-11-22 20:14 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
> /result

でた、result！命名アンチパターンだって。

2020-11-22 21:30 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
修正します。
resultではなく、`search_products`とします。

2020-11-22 21:37 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): GET /registration-details")
sessionで持つ、というのに修正していきます。

2020-11-24 07:54 UTC, tomoya-sforzando commented on templates/search.html
> +<label>
> HTML の <label> 要素は、ユーザーインターフェイスの項目のキャプションを表します。

とあるので、フォームなどの要素がないところでは使うのがおかしいですね。

cf. [<label> - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/label)

2020-11-24 07:54 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert response.status_code == 200
例えばなのですが、`サーカスTC`で検索した結果の一覧ページでは、複数回 `サーカスTC` って文字列が使われていると思うので、それをチェックしたいですね。（リスト表示されていることを確認したいです。）
`assert response.data.decode("utf-8").count("サーカスTC") > 1`
こんな感じでいけたりしないかしら？

2020-11-24 07:54 UTC, tomoya-sforzando commented on main.py
> +    product_list = amazon_api_client.search_products(keywords=keyword)
PR#26 に関係していますが、
`keyword` があるときに、`amazon_api_client.search_products()` を実行したいですね
その実行がErrorとなることも考えられるので、例外処理もほしいです

2020-11-24 08:01 UTC, yusuke-sforzando commented on templates/search.html
> +<label>
承知しました！修正します！

2020-11-24 08:01 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert response.status_code == 200
ちょっとやってみます！

2020-11-24 08:30 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert response.status_code == 200
問題なさそうなので修正しました！

2020-11-24 10:10 UTC, shin-sforzando requested changes

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +    if keyword:
`context_dict` に代入してから `keyword` の存在チェック？
存在してなかったらそもそも `keyword` を使わないのに？

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +        "subtitle": template_filename,
サブタイトルに `search.html` って表示されると誰が嬉しいんですかね？

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +            context_dict["product_list"] = product_list
変数作る必要がわからん。

```suggestion
            context_dict["product_list"] = amazon_api_client.search_products(keywords=keyword)
```

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +        app.logger.info(f"search(): GET /{request.full_path}")
これじゃ、 `query` がなくてアクセスされた時のログが取れてないじゃん。

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +    app.logger.info("search(): POST /registration")
`methods=["GET", "POST"]` って書いてるんだから、このログじゃ嘘でしょ。

2020-11-24 10:10 UTC, shin-sforzando commented on main.py
> +        "asin": asin
`context_dict` に代入してから `asin` の存在チェック？
存在してなかったらそもそも `asin` を使わないのに？

2020-11-24 10:10 UTC, shin-sforzando commented on templates/search.html
> +</div>
単純に見た目としてどうなの？

2020-11-24 10:10 UTC, shin-sforzando commented on tests/test_main.py
> +    assert response.status_code == 200
> リスト表示されていることを確認したい

それは単体テストの仕事ではなくE2Eテストの仕事では？

2020-11-24 11:08 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert response.status_code == 200
なるほど。失礼しました。

2020-11-24 12:39 UTC, yusuke-sforzando commented on main.py
> +    if keyword:
修正します。

2020-11-24 12:40 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": template_filename,
こちらも、search resultに修正します。

2020-11-24 12:40 UTC, yusuke-sforzando commented on main.py
> +    app.logger.info("search(): POST /registration")
GETの時と、POSTの時で条件を設定します。

2020-11-24 12:41 UTC, yusuke-sforzando commented on main.py
> +        "asin": asin
こちらも、同様に修正します。

2020-11-24 12:43 UTC, yusuke-sforzando commented on templates/search.html
> +</div>
この見た目、とは
コードの綺麗さ、ということでしょうか。
それとも、ページとして、検索結果の表示が見た目的によくない、ということでしょうか。

2020-11-24 13:54 UTC, shin-sforzando commented on templates/search.html
> +</div>
検索結果の見た目としてイマイチ。
何件ヒットしたのがわからなければ、一件がどこからどこまでなのかもわからない。

2020-11-24 13:57 UTC, shin-sforzando commented on main.py
> +        "subtitle": template_filename,
あのさ、日本語UIなのか英語UIなのか、はっきりして。

2020-11-25 03:30 UTC, yusuke-sforzando commented on templates/search.html
> +</div>
何件ヒットしたのか、わかるように表示します。

一件がどこからどこまでなのか分かりづらい、という点は#18のIssuesで対応します。

2020-11-25 06:37 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": template_filename,
英語UIで統一します。

2020-11-25 07:03 UTC, tomoya-sforzando commented on main.py
> +        "subtitle": template_filename,
@yusuke-sforzando さん、英語UIで統一する？

2020-11-25 07:07 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": template_filename,
@tomoya-sforzando さん
英語で統一しようと思っているのですが、何か問題ありますでしょうか？

2020-11-25 07:16 UTC, tomoya-sforzando commented on main.py
> +        "subtitle": template_filename,
いえ、英語UIで統一するなら、それで良いです。PR #29 での詳細表示なども全て英語に直す必要はあります。

2020-11-25 07:19 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": template_filename,
それでは英語で統一させていただきます。
英語での統一という共有ができておらず、申し訳ありません。

以降のIssues、PR、画面遷移図等は修正させていただきます。

2020-11-26 21:51 UTC, tomoya-sforzando reviewed
コメントしておきます

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +@app.route("/search", methods=["GET", "POST"])
`POST /search`はない

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +        app.logger.info(f"search(): POST /{request.full_path}")
`POST /search`はない

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +        "subtitle": "a service that displays search results."
subtitleって、ページのタイトルに使われる感じだから、
```suggestion
        "subtitle": "Search results for {{ keyword }}"
```
とか？

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +            context_dict["item_hits"] = item_hits
```suggestion
            context_dict["item_hits"] = len(product_list)
```

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +@ app.route("/registration", methods=["GET", "POST"])
`GET  /registration`リクエストされたら、メッセージ付きでindexにリダイレクトさせる？

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +                context_dict["asin"] = product.asin
Issue #13 で対応するところなので、以下のような感じで、追記しておいてください
`TODO: Convert Asset() from product.`

2020-11-26 21:51 UTC, tomoya-sforzando commented on main.py
> +    return render_template("registration.html", **context_dict)
asinがなかったり、なんかの拍子で`GET /registration`されたときの処理として、
indexにリダイレクトか、もしくは、
もし`session["product_list"]` があるようだったら、`GET /search`にリダイレクトさせて、
`search()` の方で、`if session["product_list"]:` であれば、`amazon_api_client.search_products()` しないで、セッションの値をそのままもう一回 `context["product_list"]` としてあげれば、無駄なAPIコールしないで、リスト表示のページに戻れるかな。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +@app.route("/search", methods=["GET", "POST"])
失礼しました。修正します。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +        app.logger.info(f"search(): POST /{request.full_path}")
修正します。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": "a service that displays search results."
そうですね、修正します。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +@ app.route("/registration", methods=["GET", "POST"])
そうですね、直接リクエストされた時は、`/search`の時と同様に戻してあげることにします。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +                context_dict["asin"] = product.asin
承知しました。

2020-11-27 02:12 UTC, yusuke-sforzando commented on main.py
> +    return render_template("registration.html", **context_dict)
なるほどですね、そのあたりの処理も追記します。
無駄なAPIリクエストは避けたいのでやってみます。

2020-11-27 06:37 UTC, tomoya-sforzando requested changes

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +    if session.get("product_list", ""):
条件分岐に関してなのですが、
1. ちゃんとqueryを受け取っているかどうか
    - → 受け取ってなかったら、indexへ
2. sessionで保持しているか
    - → 3. 保持しているsessionのproduct_listが同じqueryによるものかどうか
            - → 同じなら、sessionの内容を使ってsearchへ
            - → 違うなら、Amazon PA-APIから情報取得し、searchへ 
    - → 保持してなかったら、Amazon PA-APIから情報取得し、searchへ 

こんな順番の判別になってくるかなと思ったのですが、どうでしょうか？
とすると、queryもsessionに突っ込んでいて良いかもですね。

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +        app.logger.info(f"registration: GET /{request.full_path}")
```suggestion
        app.logger.info(f"registration: GET {request.full_path}")
```

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +        app.logger.info(f"registration: POST /{request.full_path}")
elseがいらなくって、debugレベルでformの内容をログ出力しても良さそう？
```suggestion
    app.logger.info(f"registration: POST {request.full_path}")
    app.logger.debug(f"{request.form=}")
```

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +        "subtitle": "a service that displays detailed information about the item."
ここはなんて書くか悩むけど、ページタイトル的に、`"Registration for details of asset"` とか？ 
（assetのところに登録しようとしている備品名が入っても良いかもだけどもね。それは次のIssueでも良いか。）

2020-11-27 06:37 UTC, tomoya-sforzando commented on main.py
> +    return render_template("registration.html", **context_dict)
`return render_template` するのが同じインデントレベルにあるように書かれていると読みやすいのですが、もうちょっと工夫できそうですか？

2020-11-27 06:37 UTC, tomoya-sforzando commented on templates/registration.html
> +{% endif %}
labelの使い方がおかしいです
ここでも`<h1>`タグで、`Registration for details of asset` とかそんなタイトルをつけておいて良いかもです。
subtitleと同じなら`<h1>{{ subtitle }}}</h1>`で良いですね。

2020-11-27 06:37 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert flask.request.path == '/'
ここはどうして追加した？

2020-11-27 06:37 UTC, tomoya-sforzando commented on tests/test_main.py
> +    assert b"kindle" in response.data
これがsessionのテストになってる？

2020-11-27 06:47 UTC, yusuke-sforzando commented on main.py
> +    return render_template("registration.html", **context_dict)
そうですね、すいません。
修正します。

2020-11-27 06:47 UTC, yusuke-sforzando commented on templates/registration.html
> +{% endif %}
承知しました。
修正します。

2020-11-27 06:47 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert flask.request.path == '/'
失礼しました。
不要ですね、修正します。

2020-11-27 06:47 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert b"kindle" in response.data
そのつもりで書いていますが、もっとちゃんと書きたいです。

2020-11-27 06:47 UTC, yusuke-sforzando commented on main.py
> +        "subtitle": "a service that displays detailed information about the item."
分かりました。ありがとうございます。
ページタイトルのみ修正します。

2020-11-27 06:47 UTC, yusuke-sforzando commented on main.py
> +            raise ae
承知しました。
メッセージで伝えます。

2020-11-27 06:51 UTC, yusuke-sforzando commented on main.py
> +    if session.get("product_list", ""):
そうですね、修正してみます。ありがとうございます。

2020-11-27 06:58 UTC, shin-sforzando requested changes

2020-11-27 06:58 UTC, shin-sforzando commented on __init__.py
> +SESSION_TYPE = "filesystem"
GAEって通常のファイル書き込みできないと思うよ。
cf. https://cloud.google.com/appengine/docs/standard/python3/using-temp-files?hl=JA

2020-11-27 06:58 UTC, shin-sforzando commented on __init__.py
> +app.config.from_object(__name__)
これってどこの何の設定を読み込んでるんですか？

2020-11-27 06:58 UTC, shin-sforzando commented on .gitignore
> +flask_session/
ちゃんと別項と1行開けてください。

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +    app.logger.info(f"search(): GET /{request.full_path}")
```suggestion
    app.logger.info(f"search(): GET {request.full_path}")
```

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +        context_dict["product_list"] = session["product_list"]
`context_dict` にいちいち代入せずにJinja側で直接session読み出せないの？
cf. https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/templating.html

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +        context_dict["item_hits"] = len(session["product_list"])
件数をわざわざ渡す必要ありますかねぇ。
cf. https://jinja.palletsprojects.com/en/2.11.x/templates/#length

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +        app.logger.info(f"registration: GET /{request.full_path}")
```suggestion
        app.logger.info(f"registration: GET {request.full_path}")
```

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +        app.logger.info(f"registration: POST /{request.full_path}")
POSTの `full_path` 見てなんか意味あるっけ？

2020-11-27 06:58 UTC, shin-sforzando commented on main.py
> +                # TODO: Convert Asset() from product.
```suggestion
                # TODO: Convert Asset() from product
```

2020-11-27 06:58 UTC, shin-sforzando commented on templates/registration.html
> +{% extends "_base.html" %}
List the search result with Amazon API と言うPRに `registration.html` は要らないのでは？

2020-11-27 07:01 UTC, shin-sforzando commented on templates/registration.html
> +{% endif %}
`<label>` について指摘されるの、何回目ですか？
不毛なので、いい加減、ちゃんと仕様書読んで。
cf. https://developer.mozilla.org/ja/docs/Web/HTML/Element/label

2020-12-05 09:58 UTC, tomoya-sforzando commented
wontfixでclose

2020-12-05 09:58 UTC, closed without merging