Implement header
sforzando/q-lako pull request #28
Opened 2020-11-21 11:46 UTC by tomoya-sforzando

## Describe the PR

To close #8 .

## Screenshots

window width: 1024px → app's width: 1280px
<img width="1280" alt="Screen Shot 2020-11-21 at 20 21 15" src="https://user-images.githubusercontent.com/40506652/99876244-e06d9200-2c38-11eb-9262-24f0e8c2df1b.png">

window width: 1920px → app's max width: 1280px
<img width="1280" alt="Screen Shot 2020-11-21 at 20 21 51" src="https://user-images.githubusercontent.com/40506652/99876252-eb282700-2c38-11eb-98c7-67a227fce574.png">

## Detail of the change

- Set q-lako logo and name
    - with link to "/" (index.html)
- Set background color for header
    - pick color code from g-lako icon
    - color code: `#393e46`
- Remove _footer.html
    - because it is unnecessary
- Attach container class of Tailwind CSS to `<body>`
    - for setting breakpoints automatically

## Anticipated impacts

None.

## To reproduce

Steps to check the behavior:

1. `source venv/bin/activate`
1. `python main.py`
1. Access `http://127.0.0.1:8888` with browser

## Additional context

None.

2020-11-21 15:14 UTC, shin-sforzando commented
g-lako icon??

2020-11-21 15:20 UTC, shin-sforzando requested changes
なんで `_footer.html` 消したんですか？
copyrightとかどこに書くの？

2020-11-21 15:20 UTC, shin-sforzando commented on templates/_base.html
> +<body class="container mx-auto">
bodyにCSS当ててたら `_header.html` の使い回ししにくくなります。

2020-11-21 15:20 UTC, shin-sforzando commented on templates/_header.html
> +  <nav class="p-2" style="background-color: #393e46;">
なんで色をハードコーディングしてるんですか？

2020-11-21 15:20 UTC, shin-sforzando commented on templates/_header.html
> +        <img src="static/images/logo.png" class="h-16 mr-2" />
`alt` がない。

2020-11-22 08:13 UTC, tomoya-sforzando reviewed
footerにコピーライトを追加します

2020-11-22 08:13 UTC, tomoya-sforzando commented on templates/_base.html
> +<body class="container mx-auto">
そうですね。cantainerで全体を覆うと1箇所書けばよいかと思ったのですが、ご指摘なことも確かにあるので、それぞれ(index.html, _header.html, _footer.html)で適応させます

2020-11-22 08:13 UTC, tomoya-sforzando commented on templates/_header.html
> +  <nav class="p-2" style="background-color: #393e46;">
`static/css/q-lako.css` を用意することにします

2020-11-22 08:13 UTC, tomoya-sforzando commented on templates/_header.html
> +        <img src="static/images/logo.png" class="h-16 mr-2" />
追加します

2020-11-22 10:47 UTC, shin-sforzando requested changes
> そうですね。 cantainer で全体を覆うと1箇所書けばよいかと思ったのですが、ご指摘なことも確かにあるので、それぞれ( index.html , _header.html , _footer.html )で適応させます

それなら `<div class="container">` を用意すべきですね。 `<body>` は区分化ルートタグなので、不用意にスタイリングされてると気持ち悪いです。

2020-11-22 10:47 UTC, shin-sforzando commented on templates/_base.html
> +  <link href="static/css/q-lako.css" rel="stylesheet">
固有名詞を使わない方が良いです。慣例に沿って、 `base.css` とか `common.css` とか。

2020-11-22 10:47 UTC, shin-sforzando commented on templates/_base.html
>      ga("create", "UA-XXXXX-Y", "auto"); ga("set", "anonymizeIp", true); ga("set", "transport", "beacon"); ga("send", "pageview")
GAも `_footer.html` で良いんじゃないですか。

2020-11-22 10:47 UTC, shin-sforzando commented on static/css/q-lako.css
> +.q-lako-bg-color {
命名がよくわからない。
q-lakoで使ってるのは自明なんだから、 `bg-color` と言ってるのと情報量変わらない。
そう考えたときに「 `bg-color` じゃ何のbackground色なのかわからないな」と思うなら、より適切な名前を探るべき。

2020-11-22 10:47 UTC, shin-sforzando commented on templates/_footer.html
> +  <p class="text-white text-xs text-center">Copyright&copy;2020 sforzando LLC. & Inc. All Rights Reserved.</p>
cf. https://hajipion.com/2288.html#2

2020-11-22 10:47 UTC, shin-sforzando commented on templates/_base.html
> +    <p class="text-center">TODO: Show "{{ message }}" as a flash message.</p>
`message` がないときは非表示にしないと。
cf. https://flask.palletsprojects.com/en/1.1.x/patterns/flashing/

2020-11-22 11:07 UTC, tomoya-sforzando commented on templates/_base.html
> +  <link href="static/css/q-lako.css" rel="stylesheet">
`common.css` に変更します

2020-11-22 11:08 UTC, tomoya-sforzando commented on templates/_base.html
>      ga("create", "UA-XXXXX-Y", "auto"); ga("set", "anonymizeIp", true); ga("set", "transport", "beacon"); ga("send", "pageview")
なるほど。そうですね。転記します。

2020-11-22 11:26 UTC, tomoya-sforzando commented on static/css/q-lako.css
> +.q-lako-bg-color {
`custom-color-gray` と `custom-color-blue` と2色用意しておくとよいかな。これならbackgroundだけでなく、ところどころ使用するのに記述しても違和感はなくなるかな。

2020-11-22 11:28 UTC, shin-sforzando commented on static/css/q-lako.css
> +.q-lako-bg-color {
Tailwind界隈だと `theme-` とかよく見ますね。

2020-11-22 11:30 UTC, tomoya-sforzando commented on templates/_footer.html
> +  <p class="text-white text-xs text-center">Copyright&copy;2020 sforzando LLC. & Inc. All Rights Reserved.</p>
`&copy; 2020 sforzando LLC. & Inc.` で良さそうですね。

2020-11-22 11:30 UTC, tomoya-sforzando commented on static/css/q-lako.css
> +.q-lako-bg-color {
ありがとうございます。`theme-color-gray`, `theme-color-blue` でいきます

2020-11-22 11:36 UTC, tomoya-sforzando commented on templates/_base.html
> +    <p class="text-center">TODO: Show "{{ message }}" as a flash message.</p>
flash message自体は、#10 や #17 で実装予定ですので、`{% if message %}` とだけ追加しておきます

2020-11-22 12:15 UTC, yusuke-sforzando submitted a review, later dismissed
LGTM.

2020-11-22 13:01 UTC, shin-sforzando commented on templates/_base.html
> +  <div class="container mx-auto flex flex-col h-screen">
header, footerってfull widthじゃなくて良いのかな。

2020-11-22 13:32 UTC, tomoya-sforzando commented on templates/_base.html
> +  <div class="container mx-auto flex flex-col h-screen">
a. headerとfooterにそれぞれ Tailwind CSSの `w-full` をあてた方がよいということですか？
b. それとも、containerのレスポンシブなエリアにheaderとfooterは引っ張られない方がよいということでしょうか？

aに関しては、現状あてなくても意図通りに表示できているから、要素が増えたりして、記述が必要になったらで良いかなと思っています
b.に関しては、windowサイズがすごく大きな時に、headerもfooterも横一杯に広がっていない方が、良いかなーと思ったのですが、そんなことないです？

どうでしょうか？

2020-11-22 13:35 UTC, tomoya-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
`<meta name="theme-color" content="#fafafa">` に対して、 cssの変数あてるのって何か良い方法あります？
ベタ書きは、なし？

2020-11-22 14:10 UTC, shin-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
Flask側に持たせるとか？

2020-11-22 14:11 UTC, shin-sforzando commented on templates/_base.html
> +  <div class="container mx-auto flex flex-col h-screen">
という調整がしにくい、というのが問題と思います。

2020-11-22 14:18 UTC, tomoya-sforzando commented on templates/_base.html
> +  <div class="container mx-auto flex flex-col h-screen">
ふーむ。だったら、最初に指摘してもらった通り、全体を一つのcontainerで囲ってしまうのは悪手ですね。
別個に当てるように戻します。

2020-11-22 14:32 UTC, tomoya-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
> Flask側に持たせるとか？
うーん。あまりきれいに処理書ける自信ないけど、ちょっとやってみます。

2020-11-22 16:09 UTC, tomoya-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
こんな感じかなぁ。
commit - https://github.com/sforzando/q-lako/pull/28/commits/9fa9dda49ee090b5bc3388c529ec4186fe4b260c
<img width="1783" alt="Screen Shot 2020-11-23 at 0 39 07" src="https://user-images.githubusercontent.com/40506652/99908868-7cc29200-2d28-11eb-997b-6c015667ab41.png">

2020-11-22 16:22 UTC, shin-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
いや、これはないだろ、jk
この色をロゴ画像から取ってきたと言うのなら、 `settings.ini` あたりにテーマカラーを持っておいて、CSSを作る方が健全。

2020-11-22 17:01 UTC, tomoya-sforzando commented on templates/_base.html
>    <meta name="theme-color" content="#fafafa">
CSSファイル生成ですか。やってみますね。

2020-11-23 09:08 UTC, tomoya-sforzando commented
静的に用意する `common.css` と動的に生成する `generated.css` とを用意し、`common.css` の方で `generated.css` をインポートするようにしました。`generated.css` はアプリの初期化時に毎回生成しなおすようにしています。

2020-11-23 11:37 UTC, shin-sforzando requested changes

2020-11-23 11:37 UTC, shin-sforzando commented on __init__.py
> +    css_theme_color = ":root {\n" + \
f-strings使おうよ。

2020-11-23 11:37 UTC, shin-sforzando commented on static/css/common.css
> +  color: var(--theme-color-blue);
どう考えても冗長すぎ。
直接 `common.css` 書き換えれば良いじゃん。

2020-11-23 11:37 UTC, shin-sforzando commented on main.py
> +        "theme_color": app.config["THEME_COLOR"],
こうやっちゃったら他の呼び出しにも必ずこれを添えなきゃいけなくなるよ？

2020-11-23 11:37 UTC, shin-sforzando commented on README.md
> +[DEFAULT]
`[default]` が取り止めもなくなってるからちゃんと分けて。

2020-11-23 15:19 UTC, tomoya-sforzando commented
common.css は静的に記述しておくものの出てくるかと思うので、該当箇所を `settings.ini` からの値でアップデートするような処理にしました。

2020-11-23 15:35 UTC, yusuke-sforzando approved these changes, later dismissed
LGTM.

2020-11-23 16:31 UTC, shin-sforzando requested changes

2020-11-23 16:31 UTC, shin-sforzando commented on __init__.py
> +# Update css with theme color in settings.ini
`settings.ini` を書き換えない限り必要ない処理を毎起動ごとに行う必要性がわからない。
シェルスクリプトでテンプレートを元に`common.css` (必要なら `_base.html` も)置換生成できるやつを用意してREADME.mdに書いて終わりで良くない？

2020-11-23 16:31 UTC, shin-sforzando commented on __init__.py
> +with open(css_file_path, mode="r") as rf:
仮にPythonでやるにしても、せめて `fileinput` 使いません？
cf. https://docs.python.org/ja/3/library/fileinput.html

2020-11-23 16:31 UTC, shin-sforzando commented on __init__.py
> +        if "theme-color-blue" in line:
あれ、しかもこの書き方だと置換じゃなくて追記してません？

2020-11-24 06:48 UTC, tomoya-sforzando commented on __init__.py
> +# Update css with theme color in settings.ini
>シェルスクリプトでテンプレートを元に common.css (必要なら _base.html も)置換生成できるやつを用意してREADME.mdに書いて終わりで良くない？

おっしゃることはもっともですね。その方針が最適解な気がします。
その実装については、別Issueとして切り分け、
こちらのPRでは`settings.ini`の値からの`meta`タグへのtheme colorの代入、`common.css`から`header`, `footer`でのtheme colorの使用までとさせてください。

2020-11-24 08:21 UTC, shin-sforzando requested changes

2020-11-24 08:21 UTC, shin-sforzando commented on README.md
> +[Common]
名前が悪い。  `Common` ってなんの情報量もないじゃん。

2020-11-24 11:48 UTC, tomoya-sforzando commented on README.md
> +[Common]
候補を考えてみたのですが、 `Appearance`, `Design`, `Visual`とかで、見た目に関係するセッションとしてまとめようかと思います。
この中では、`Appearance`が良いかなと思っていますが、どうでしょう？

2020-11-24 13:59 UTC, shin-sforzando commented on README.md
> +[Common]
俺なら普通に `THEME-COLOR` にするけど。

2020-11-24 16:30 UTC, shin-sforzando requested changes

2020-11-24 16:30 UTC, shin-sforzando commented on __init__.py
> +app.config["THEME_COLOR"] = config_parser.get("THEME-COLOR", "theme_color_gray")
theme-colorが2色あって、片方しかセットしないなら。

```suggestion
app.config["THEME_COLOR"] = config_parser.get("THEME-COLOR-GRAY", "theme_color_gray")
```

2020-11-24 16:30 UTC, shin-sforzando commented on README.md
> +  - [Prepare `settings.ini`](#prepare-settingsini)
`.env` の方が影響範囲広いから章立ての順は `.env` → `settings.ini` 。
(DEBUGなら、こっちのセッティング、PRODなら、こっち、ってのはよくある)

2020-11-24 16:30 UTC, shin-sforzando commented on README.md
> +```INI
```suggestion
```settings.ini
```

2020-11-24 16:30 UTC, shin-sforzando commented on static/css/common.css
> +  background-color: #393e46;
ここは `var` を使ってませんでした？

2020-11-24 16:30 UTC, shin-sforzando commented on templates/_header.html
> +      <img class="h-16 mr-2" src="static/images/logo.png" alt="logo image of q-lako" />
altもFlash messageも、英語UIなのか日本語UIなのか統一してくれませんか。

2020-11-24 17:27 UTC, tomoya-sforzando commented on templates/_header.html
> +      <img class="h-16 mr-2" src="static/images/logo.png" alt="logo image of q-lako" />
日本語化するにあたって、サブタイトルにあたっている `a service to quickly register equipments and books` は `備品・書籍をらくらく登録` とかでどうでしょうか？ 「クイックに/はやく」っていうのが入っていないのですが「らくらく」っていうのが音として q-lakoにも近くてありかなーと思ったのですが。

2020-11-25 10:53 UTC, tomoya-sforzando commented on templates/_header.html
> +      <img class="h-16 mr-2" src="static/images/logo.png" alt="logo image of q-lako" />
こちらは、英語UIに統一ということになりました

2020-11-25 13:13 UTC, yusuke-sforzando commented
LGTMです。ありがとうございます。

2020-11-25 13:14 UTC, yusuke-sforzando approved these changes
LGTMです。ありがとうございます。

2020-11-25 14:19 UTC, shin-sforzando approved these changes
これをcloseしないと他のPRがわけわかんないので、いったんマージしましょう。

2020-11-26 05:07 UTC, merged