Refactoring code
sforzando/q-lako pull request #33
Opened 2020-12-05 07:28 UTC by tomoya-sforzando

## Describe the PR

To close #32 .

## Screenshots

If applicable, add screenshots to help explain your problem.

## Detail of the change

A clear and concise description of what you changed.

## Anticipated impacts

A clear and concise description of where may be affected by the changes.

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

Add any other context about the problem here.

2020-12-05 11:41 UTC, shin-sforzando requested changes

2020-12-05 11:41 UTC, shin-sforzando commented on .flake8
>  ignore=H101,H301,H306
前にも渡邉さんに指摘したんだけどH系のエラー出ないはずなので、このリファクタリングついでに消してもらって良いですか？

2020-12-05 11:41 UTC, shin-sforzando commented on main.py
> +    U = Union[str, int]
命名が悪いし、型の宣言は冒頭が原則。

2020-12-05 11:41 UTC, shin-sforzando commented on templates/registration.html
> +            id="asin" value="{{ product.asin }}" />
ASINって書き換えれて良いの？

2020-12-05 11:41 UTC, shin-sforzando commented on main.py
> +            publication_date=convert_str_none_int_0(posted_asset.get("publication_date")),
Dateを0で返す…？

2020-12-05 11:51 UTC, tomoya-sforzando commented on main.py
> +            publication_date=convert_str_none_int_0(posted_asset.get("publication_date")),
んー、ここに関するところ、諸々確認足りてなかったので、APIドキュメント見直して修正します。

2020-12-05 11:52 UTC, tomoya-sforzando commented on templates/registration.html
> +            id="asin" value="{{ product.asin }}" />
確かに書き換えることもないですね。固定値にします

2020-12-06 10:02 UTC, tomoya-sforzando commented on main.py
> +            publication_date=convert_str_none_int_0(posted_asset.get("publication_date")),
`publication_date` について、そもそも`None`で登録できるのに、わざわざ登録できないformatおよびパターンでの`'None'`となっていたので、その辺り修正しました。

2020-12-06 10:03 UTC, tomoya-sforzando commented on main.py
> +            publication_date=convert_str_none_int_0(posted_asset.get("publication_date")),
入力時のフォーマットのバリデーションも追加しました
`required`の項目ではないので、空白のまま`submit`すれば`None`で登録されます
<img width="794" alt="Screen Shot 2020-12-06 at 17 31 03" src="https://user-images.githubusercontent.com/40506652/101277156-c2d22800-37f5-11eb-9931-7d39cc9e0b48.png">

2020-12-06 10:06 UTC, tomoya-sforzando commented on main.py
> +    U = Union[str, int]
> 命名が悪いし、型の宣言は冒頭が原則。

`publication_date`の型と入力周りの見直しにより不要になったので、削除しました

2020-12-06 10:08 UTC, shin-sforzando approved these changes

2020-12-06 10:46 UTC, yusuke-sforzando commented on main.py
> +            publication_date=convert_str_none_int_0(posted_asset.get("publication_date")),
承知しました。ありがとうございます。

2020-12-06 10:49 UTC, yusuke-sforzando approved these changes
LGTMです。
ありがとうございました。

2020-12-06 10:51 UTC, merged