025 implement tailwind css
sforzando/q-lako pull request #35
Opened 2020-10-07 20:13 UTC by yusuke-sforzando

## Describe the PR

To close #25 Implement Tailwind CSS.

## Screenshots

<img width="1671" alt="Screen Shot 2020-10-08 at 5 11 00" src="https://user-images.githubusercontent.com/67737076/95382484-ad8b6b00-0924-11eb-939f-754e8d287b7b.png">

## Detail of the change

(T.B.D.)

## Anticipated impacts

(T.B.D.)
## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D.)

2020-10-08 07:46 UTC, tomoya-sforzando approved these changes

2020-10-08 08:21 UTC, shin-sforzando requested changes
<img width="826" alt="Screen Shot 2020-10-08 at 17 07 49" src="https://user-images.githubusercontent.com/32637762/95433193-954e3700-098a-11eb-8626-09a697f5d12a.png">
HTML5仕様に沿ってない箇所が少なくとも3箇所あるようです。

2020-10-09 04:57 UTC, shin-sforzando requested changes

2020-10-09 04:57 UTC, shin-sforzando commented on .editorconfig
> +Toc: Levels 2..6
なにこれ？

2020-10-09 05:03 UTC, yusuke-sforzando commented on .editorconfig
> +Toc: Levels 2..6
VS Codeの拡張機能、MarkdownのAll in Oneを使った設定です。
これを適応すると、README.mdの目次から、1章のタイトルが省略されます。
目次を1章から設定するのではなく、2章から振り直すものです。
昨日指摘されたので、追記しました。

2020-10-09 06:28 UTC, shin-sforzando commented on .editorconfig
> +Toc: Levels 2..6
書くところ間違ってません？
[EditorConfig](https://editorconfig-specification.readthedocs.io/en/latest/#id7)の仕様にあります？

2020-10-09 06:55 UTC, yusuke-sforzando commented on .editorconfig
> +Toc: Levels 2..6
そうですね..
手元にMarkdown All in Oneの設定を書き換えたら、自動で追加されてしまったようです。
EditorConfigの仕様に含まれていません。
不要な設定でした。

2020-10-09 07:02 UTC, shin-sforzando commented on .editorconfig
> +Toc: Levels 2..6
再現しないなぁ。

2020-10-09 07:03 UTC, tomoya-sforzando requested changes
デリミタのフォーマットを直してください
cf. https://jinja.palletsprojects.com/en/2.11.x/templates/

2020-10-09 09:57 UTC, shin-sforzando requested changes

2020-10-09 09:57 UTC, shin-sforzando commented on main.py
> +@app.route("/404")
この関数、いつどうやって使うの？

2020-10-09 09:57 UTC, shin-sforzando commented on main.py
> +    context_dict["error_status"] = error_status
なんで37行目でわざわざ変数にしたの？

2020-10-09 09:57 UTC, shin-sforzando commented on main.py
> +def error_handler(error):
この `error` ってなんのために受け取ってるかわかる？

2020-10-09 09:57 UTC, shin-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
この `error_status` が404以外のことってあるの？

2020-10-09 09:57 UTC, shin-sforzando commented on tests/test_main.py
> +    response = test_client.get("/error")
`/error` はもう無いのでは？

2020-10-09 10:04 UTC, yusuke-sforzando commented on main.py
> +    context_dict["error_status"] = error_status
おっしゃる通りです...
配列にそのまま入れた方がよかったです。
修正します。

2020-10-09 10:21 UTC, yusuke-sforzando commented on main.py
> +def error_handler(error):
内部の処理がどうなっているかは理解していませんでした。
申し訳ありません。

2020-10-09 10:21 UTC, yusuke-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
このページに飛ぶ時は404以外ではないので、直接書いちゃった方がいいですね。
修正します。

2020-10-09 10:23 UTC, yusuke-sforzando commented on main.py
> +@app.route("/404")
404エラーであることを登録するために使っている、という風に理解しています。
他のエラーがあれば、これに登録して流用しようと考えていました。

2020-10-09 10:23 UTC, yusuke-sforzando commented on tests/test_main.py
> +    response = test_client.get("/error")
そうですね。
正しくは登録されているurl以外でテストする必要がありますね。
出直します。

2020-10-09 10:25 UTC, shin-sforzando commented on main.py
> +@app.route("/404")
どこ情報？公式ドキュメントに書いてあった？

2020-10-09 10:26 UTC, shin-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
HTTPステータスコードごとにhtml用意する気なら `404.html` とかのほうがわかりやすい。
ちなみにGAEのほうにもエラーハンドラの仕組みがあるのは気づいてますか？

2020-10-09 10:28 UTC, yusuke-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
気づいていませんでした。

2020-10-09 10:30 UTC, yusuke-sforzando commented on main.py
> +@app.route("/404")
このドキュメントに書いていたのですが、こんなことしなくても書けることに先ほど気付きました。
https://flask.palletsprojects.com/en/1.1.x/api/?highlight=abort#flask.abort

2020-10-09 10:48 UTC, tomoya-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
> ちなみにGAEのほうにもエラーハンドラの仕組みがあるのは気づいてますか？

現状、余計なことしてる感じがあるので、エラーハンドラはapp.yamlに追記する形で片付けてしまった方がスマートですね。
```app.yaml
error_handlers:
  - file: default_error.html
```
[app.yaml 構成ファイル  |  Python 3 の App Engine スタンダード環境  |  Google Cloud](https://cloud.google.com/appengine/docs/standard/python3/config/appref?hl=ja#handlers_element)

2020-10-09 10:50 UTC, yusuke-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
なるほど...
ではエラーページへのルーディングはFlaskを使わないものとして進めます。
スマートな方でやります。
ありがとうございます。

2020-10-09 11:05 UTC, shin-sforzando requested changes

2020-10-09 11:05 UTC, shin-sforzando commented on main.py
> +# Registering "/register" handler with Flask
なにこれ？

2020-10-09 11:07 UTC, shin-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
エラーハンドルをGAE側に任せるとE2Eテストでしか検証できなくなるのはわかってての判断だよね？

2020-10-09 11:11 UTC, yusuke-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
今回の場合は、存在のしないページへの対応のみなので、テストはE2Eテストだけで良いと考えています。
浅はかでしょうか...。

2020-10-09 11:11 UTC, yusuke-sforzando commented on main.py
> +# Registering "/register" handler with Flask
大変失礼しました。
修正いたします。

2020-10-10 03:06 UTC, shin-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
俺ならやらないですね。

理由1)
app.yamlに記述するerror_handlersはover_quotaとtimeoutを拾うためにあって、404もtimeoutとして拾えるけど、それはサーバ処理の遅延だったかNOT FOUNDだったかはログを精査しないとわからない。

理由2)
CI/CDでデプロイするたびにE2Eを回すとして、その度にStackdriverにエラーログが記載されることになる。

理由3)
GAEにデプロイしてない場面(ローカル、または他のサービスで稼働)ではerrorがhandleされない。

理由4)
404は「ページがNOT FOUND」と「要素(ex. `favicon.ico` )がNOT FOUND」、両方ありえて同じようにStackdriverに記載されるが、Flaskのerrorhandlersならページがない場合を検出可能。

理由5)
404以外の、たとえば500などはどう拾うの？
全部GAEに拾わせると、ますます「GAEが落ちてた」「GAEは落ちてないがFlaskが落ちてた」と精査しなきゃいけなくなる。

`main.py` に4,5行足すだけのことを省く割に得られるメリットが見にくいログなので、俺ならやらない。

2020-10-10 03:13 UTC, tomoya-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
勉強になりました！

2020-10-10 03:16 UTC, shin-sforzando commented on main.py
> +# Registering "/register" handler with Flask
これがなんなのか？と質問してるんだが。

2020-10-10 04:20 UTC, yusuke-sforzando commented on templates/not_found.html
> +<p class="text-4xl text-center">{{ error_status }}</p>
勉強になります…
ありがとうございました！

2020-10-10 04:25 UTC, yusuke-sforzando commented on main.py
> +# Registering "/register" handler with Flask
Flaskで/registerに来た時のハンドルを登録する、という処理のコメントを消し忘れていました。

2020-10-10 04:48 UTC, shin-sforzando commented on main.py
> +# Registering "/register" handler with Flask
コメントを書くのは良いこと、書くならちゃんとdocstringで書きましょう。
cf. https://qiita.com/simonritchie/items/49e0813508cad4876b5a

2020-10-10 08:47 UTC, shin-sforzando requested changes

2020-10-10 08:47 UTC, shin-sforzando commented on main.py
> +def bad_request(e):
Bad Requestは400ですね。
https://developer.mozilla.org/ja/docs/Web/HTTP/Status/400

2020-10-10 08:47 UTC, shin-sforzando commented on requirements.txt
> +sentry-sdk[flask]
このライブラリ、どこで使ってるの？

2020-10-10 08:52 UTC, yusuke-sforzando commented on main.py
> +def bad_request(e):
Not Foundに変更します！
ありがとうございます！

2020-10-10 08:53 UTC, yusuke-sforzando commented on requirements.txt
> +sentry-sdk[flask]
使っていませんでした。
https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/errorhandling.html
の練習で使っていたのを、消し忘れていました。
すいません。

2020-10-10 09:32 UTC, tomoya-sforzando commented on main.py
> +    raise Exception("An exception was raised.")
@shin-sforzando さん、 @yusuke-sforzando さん、
[アプリケーションのエラー — Flask Documentation (1.1.x)](https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/errorhandling.html)
を参考に、errorhandlerを追加してみたのですが、500 Internal Server Errorのテストをしたいがためだけにこちらの関数を用意したんですよね。明らかに、本来不要な関数。どうしたもんですかね？

2020-10-10 09:40 UTC, yusuke-sforzando commented on main.py
> +    raise Exception("An exception was raised.")
すいません。正直よくわからないです。

2020-10-10 09:43 UTC, shin-sforzando commented on main.py
> +    raise Exception("An exception was raised.")
500のテストは今時点で諦める、が現実解かと。

2020-10-10 09:43 UTC, shin-sforzando commented on main.py
> +    raise Exception("An exception was raised.")
俺もソース読んでてモヤっとしながらも「まぁテストしたいならこうするしかないもんなぁ」と思ってたところ。

2020-10-10 09:44 UTC, tomoya-sforzando commented on main.py
> +    raise Exception("An exception was raised.")
なるほど。ありがとうございます。
では、現時点では、諦めるとして、500のテストに関する部分は削除します。

2020-10-10 10:05 UTC, shin-sforzando requested changes

2020-10-10 10:05 UTC, shin-sforzando commented on templates/index.html
> +<p class="text-4xl text-green-700 text-center">{{ message }}</p>
これ、register.htmlと何も変わらなくてbase.htmlをextendsしてるなら、base.htmlに書き込んでおいてそれぞれのテンプレートは何も書かない方がDRYなのでは？

2020-10-10 10:05 UTC, shin-sforzando commented on templates/error.html
> +  <h class="text-4xl">{{ e_title }}</h>
`<h>` なんてあったっけ？

2020-10-10 10:05 UTC, shin-sforzando commented on templates/error.html
> +  <p>{{ e_description }}</p>
base.html継承するなら、 `subtitle` と `message` 使わないのはなんで？

2020-10-10 10:07 UTC, tomoya-sforzando commented on templates/error.html
> +  <h class="text-4xl">{{ e_title }}</h>
ないですね。ミスです。直します。

2020-10-10 10:07 UTC, tomoya-sforzando commented on templates/error.html
> +  <p>{{ e_description }}</p>
確かに。直します。

2020-10-10 10:08 UTC, tomoya-sforzando commented on templates/index.html
> +<p class="text-4xl text-green-700 text-center">{{ message }}</p>
そうですね。そうしましょう。

2020-10-10 10:54 UTC, shin-sforzando approved these changes
LGTM

2020-10-10 10:57 UTC, tomoya-sforzando approved these changes
では、こちらはマージします

2020-10-10 10:57 UTC, merged