Fix registration
sforzando/q-lako pull request #41
Opened 2020-12-09 09:33 UTC by tomoya-sforzando

## Describe the PR

To close #39 .

## Screenshots

|Before|After|
|---|---|
|<img width="1291" alt="Screen Shot 2020-12-07 at 15 08 52" src="https://user-images.githubusercontent.com/32637762/101315915-d84f5c80-389e-11eb-811e-d2aec1255495.png">|<img width="1499" alt="Screen Shot 2020-12-09 at 18 18 56" src="https://user-images.githubusercontent.com/40506652/101610416-90216d00-3a4b-11eb-9f76-0bf480c3d3bc.png">|

## Detail of the change

- Fix `Contributors`
- Change format of `Production date`
    - e.g. `December 05, 2020`
- Set required to `Default position` and `Current position`
- Remove `None` from `Features`
- Fix order of form

## Anticipated impacts

None.

## To reproduce

Steps to check the behavior:

1. `source venv/bin/activate`
1. `python main.py`
1. Access `http://127.0.0.1:8888` with browser

## Additional context

None.

2020-12-10 00:59 UTC, yusuke-sforzando commented on main.py
> +                print(f"{product.info.contributors=}")
ここの`print`文は必要だったりしますか？

2020-12-10 00:59 UTC, yusuke-sforzando commented on main.py
> +                    print(f"{contributor.name=}")
ここも同様に、`print`文必要でしょうか？

2020-12-10 01:24 UTC, yusuke-sforzando reviewed
`print`文以外に気になるところは見つかりませんでした。
問題なければApproveします。
ご確認お願いします。

2020-12-10 01:24 UTC, yusuke-sforzando commented on templates/registration.html
> +            pattern="^(January|February|March|April|May|June|July|August|September|September|November|December) [0-9]{2}, [0-9]{4}$" />
なるほど、ここはこのように実装するのですね。

2020-12-10 06:46 UTC, shin-sforzando requested changes
<img width="1277" alt="Screen Shot 2020-12-10 at 15 35 46" src="https://user-images.githubusercontent.com/32637762/101731373-e56a8680-3afe-11eb-8ee0-a7d92d1cfe99.png">

2020-12-10 06:46 UTC, shin-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
なんで文字列スライスを使うの？

2020-12-10 06:46 UTC, shin-sforzando commented on templates/registration.html
> +            pattern="^(January|February|March|April|May|June|July|August|September|September|November|December) [0-9]{2}, [0-9]{4}$" />
`October` はどこ行った。

2020-12-10 07:16 UTC, tomoya-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
`fromisoformat`はタイムゾーンの`Z`が対称でなく、Amazon PA-APIから取得データは`2009-07-01T00:00:01Z`いった形で、ここで利用したいのは日付までなので、先方10文字を利用すれば十分だなという判断です。
それと、Amazon PA-APIからのレスポンスとしていくつか取得してわかったのは、`2009-07-01`とだけ返ってくるものもあったので、上記の判断になりました。
https://docs.python.org/ja/3/library/datetime.html#datetime.datetime.fromisoformat
https://webservices.amazon.com/paapi5/documentation/item-info.html#contentinfo

2020-12-10 07:17 UTC, tomoya-sforzando commented on templates/registration.html
> +            pattern="^(January|February|March|April|May|June|July|August|September|September|November|December) [0-9]{2}, [0-9]{4}$" />
`September` が被って `October` がなかったです。修正します

2020-12-10 08:36 UTC, shin-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
じゃあ尚更、ある日 `Jan 3, 2021` が返ってくる日が来るかもしれない、とは思いませんか？
`10` みたいなマジックナンバーを気軽に使われてるのが嫌なんですよね。
最終的にDateTimeにするなら、用意されている適切なメソッドを呼ぶか、
https://docs.python.org/ja/3/library/datetime.html#strftime-strptime-behavior
せめてコメントつけませんか。

2020-12-10 16:33 UTC, tomoya-sforzando commented on main.py
> +                print(f"{product.info.contributors=}")
printは不要です。削除します。

2020-12-10 16:33 UTC, tomoya-sforzando commented on main.py
> +                    print(f"{contributor.name=}")
printは不要です。削除します。

2020-12-10 18:20 UTC, tomoya-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
Amazon PA-APIから取得できる値が`2009-07-01T00:00:01Z`といった形の`str`で、使いたい形も`2009-07-01`という`str`なので、datetimeに変更する必要もなく、正規表現でマッチする場合にその部分を抜き出し、そうでない場合は`None`とするようにしました。（先は`May 12, 2020`のような表記に変換したかったので、datetimeにしていた。）

入力フォームの方は、`type="date"` にすることにより、このような形に落ち着きました。
<img width="816" alt="Screen Shot 2020-12-11 at 2 59 32" src="https://user-images.githubusercontent.com/40506652/101813045-90129180-3b5f-11eb-83dc-d5c095221cdb.png">

2020-12-10 18:22 UTC, tomoya-sforzando commented
`Registrant` の入力も、セレクトフォームに修正しています。
<img width="802" alt="Screen Shot 2020-12-11 at 2 59 47" src="https://user-images.githubusercontent.com/40506652/101813454-19c25f00-3b60-11eb-82e2-7b872402a7fe.png">

2020-12-10 19:35 UTC, shin-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
> Amazon PA-APIから取得できる値が2009-07-01T00:00:01Zといった形のstrで

だから、未来永劫に渡ってその保証がないから、マジックナンバー使うなって言ってるんだが？
cf. https://yoru9zine.hatenablog.com/entry/2016/11/23/174953

2020-12-10 19:59 UTC, shin-sforzando requested changes

2020-12-10 19:59 UTC, shin-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
strftimeを使うべき。タイムゾーンを捨てるのも好ましくない。

2020-12-11 02:30 UTC, tomoya-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
> だから、未来永劫に渡ってその保証がないから、マジックナンバー使うなって言ってるんだが？

はい、なので、`[:10]`みたいのでなくて、
> 正規表現でマッチする場合にその部分を抜き出し、そうでない場合はNoneとするようにしました。

です。正規表現はマジックナンバーではないですよね？

2020-12-11 02:37 UTC, tomoya-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
> strftimeを使うべき。タイムゾーンを捨てるのも好ましくない。

そもそもタイムゾーンを持っていないパターンがあるみたいなので、その辺りの処理も含め、もう少し考えます

2020-12-11 04:48 UTC, shin-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
なぜ「時間」を頑なに「文字列」として扱おうとするのかわからない。
デメリット列挙しないと伝わりませんか？

2020-12-11 04:59 UTC, tomoya-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
なるべく多くのパターンを拾えるように、
- タイムゾーンの表記が `Z` となっている場合の置き換え
- Amazon PA-APIからのstring_datetimeをdatetimeへ変換
- datetimeから、`<input type="datetime-local">`のためへの変換
という処理にしました。

2020-12-11 05:01 UTC, tomoya-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
Amazon PA-APIからの値に対して、多くのパターンを拾えるように正規表現と処理を調整しました。

2020-12-11 05:04 UTC, tomoya-sforzando commented on main.py
> +                product.info.publication_date = dt.fromisoformat(
`<input type="datetime-local">`に対応するようにフォーマットを調整し、以下のようになりました。
<img width="781" alt="Screen Shot 2020-12-11 at 13 42 31" src="https://user-images.githubusercontent.com/40506652/101865492-c41aa080-3bb9-11eb-9964-97ca0c6f9b5b.png">

2020-12-11 05:17 UTC, shin-sforzando requested changes

2020-12-11 05:17 UTC, shin-sforzando commented on main.py
> +                matched_str_datetime = re.search(
`_datetime` って変数名でDatetimeじゃないじゃん。

2020-12-11 05:25 UTC, tomoya-sforzando commented on main.py
> +                matched_str_datetime = re.search(
datetimeでの変換処理は、こちらです。
https://github.com/sforzando/q-lako/blob/086a57cbcf5a72224caf1d47694e09f4a8568c92/main.py#L76

やりたいことは、Amazon PA-APIからstrignなDatetimeを、Pythonでのdatetimeに変換する、そしてそのdatetimeから`<input type="datetime-local">`のための文字列のフォーマットにする。
なので、string → datetime → string をいうのを
`product.info.publication_date = dt.fromisoformat(matched_str_datetime.group()).strftime("%Y-%d-%mT%H:%M")`
でやっていることになります。

2020-12-11 05:31 UTC, shin-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
やっぱり伝わってないからデメリット列挙しますね。

(1) 正規表現はマジックナンバーではないが一瞥して何をしたいかわからない
(2) 正規表現は文字列に対して行うもの、たとえば小麦の塊をノコギリで切ってたら「工業製品なのかな？」と思うし、包丁で切ってたら「食べ物なのかな？」と思うのと一緒で、日時を相手に日時向けじゃない道具を使ってるのは読み手に語弊をもたらす
(3) strftimeはPythonも含む多くの言語で実態はCの実装をそのまま使うことになっており、高速かつ可換、一方で正規表現は方言がある(cf. https://www.javadrive.jp/regex-basic/programming/index1.html )
(4) 正規表現を使うなら、その表現が妥当かを確かめるテストをより広範に書かなければならないし、matchしなかった時、なぜmatchしなかったかわかるようにしなければならない
(5) 「多少のブレがある日時フォーマットをうまくパースしたいな」は鹿島田さんが人類史上初めて取り組む問題だと思いますか？ (cf. 
 https://opensource.com/article/18/4/python-datetime-libraries )

2020-12-11 05:47 UTC, tomoya-sforzando commented on main.py
> +                matched_str_date = re.search(r"19|20[0-9]{2}-[0-9]{2}-[0-9]{2}", product.info.publication_date)
わかりやすく示してくださってありがとうございます。(2)の感覚的なところが、これからそれがおかしいな気持ち悪いなと思えるようになる視点という意味でしっくりきました。(5)を読んで、適切に処理できるように調整します。

2020-12-11 07:44 UTC, shin-sforzando commented on main.py
> +                matched_str_datetime = re.search(
いや、当然それを知ってて、一時変数の名前もしっかりつけなよ、って指摘なんだけど？

2020-12-11 07:45 UTC, shin-sforzando commented on main.py
> +                matched_str_datetime = re.search(
てか、日時処理が3行で書けないぐらい複雑になるんだったら別関数に分けますね、俺なら。
そうすると拡張性、保守性にアドバンテージがある。

2020-12-11 07:58 UTC, tomoya-sforzando commented on main.py
> +                matched_str_datetime = re.search(
先ほどの(5)を読んで、ライブラリをそれぞれみてみて、結果、`from dateutil.parser import parse` で一発でした。無駄なことをしていました。

2020-12-11 14:06 UTC, shin-sforzando approved these changes

2020-12-11 14:25 UTC, merged