Record application logs
sforzando/q-lako pull request #42
Opened 2020-10-10 14:28 UTC by yusuke-sforzando

## Describe the PR

To close #12 
Record Application Logs.

(T.B.D)

## Screenshots

(T.B.D)

## Detail of the change

(T.B.D)

## Anticipated impacts

(T.B.D)

## To reproduce

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Additional context

(T.B.D)

2020-10-12 02:38 UTC, tomoya-sforzando commented on main.py
> +        app.logger.warning("handle_exception(): HTTP EXCEPTION")
```suggestion
        app.logger.warning(f"handle_exception(): {context_dict}")
```
error内容がわかるようにこうするとどうでしょうか？

<img width="1046" alt="Screen Shot 2020-10-12 at 11 37 16" src="https://user-images.githubusercontent.com/40506652/95699417-54eb0380-0c7f-11eb-99b3-b89501642d18.png">

2020-10-12 04:45 UTC, shin-sforzando requested changes

2020-10-12 04:45 UTC, shin-sforzando commented on main.py
> +        app.logger.warning("handle_exception(): HTTP EXCEPTION")
そもそも、そのif文の中に入らないとログが残らない方がおかしくない？
ちょっとこっちで書き換えますね。

2020-10-12 04:45 UTC, shin-sforzando commented on tests/test_main.py
> +    assert b"index.html" in response.data
このテスト文とこの下のテスト文の違いがわかりません。
何がしたいんですか？

2020-10-12 05:53 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert b"index.html" in response.data
確かに。
ステータスコードのテストが必要だと思っていたのですが、main.pyの方でそういった値が返ってくるわけではないので、不要でした。
修正します。

2020-10-12 05:59 UTC, shin-sforzando commented on tests/test_main.py
> +    assert b"index.html" in response.data
ん、何を言ってるかわからない。
ステータスコードのテストは15行目でやっている。
俺が質問してるのは13行目と14行目の違い。

2020-10-12 06:03 UTC, yusuke-sforzando commented on tests/test_main.py
> +    assert b"index.html" in response.data
なるほど、全く同じ意味のテストをしていますね。
ミスでした。すいません。

2020-10-12 09:04 UTC, shin-sforzando approved these changes
LGTM.

2020-10-12 09:17 UTC, tomoya-sforzando approved these changes
LGTM.

2020-10-12 09:17 UTC, merged

2020-12-11 08:35 UTC, yusuke-sforzando commented on tests/test_airtable_client.py
> +def test_delete_asset_failure(airtable_client):
そうですね、やってみます。